package com.baosight.tech.mode;

import java.util.Date;

/**
 * TbTechDiscoure generated by MyEclipse Persistence Tools
 */

public class TbTechDiscoure implements java.io.Serializable {

	// Fields

	private String id;

	private String pianming;

	private String zuozhe1;

	private String zuozhe2;

	private String zuozhe3;

	private String danwei;

	private String kanming;

	private Date fabiaoshijian;

	private String qihao;

	private String guanjianci;

	private String zhaiyao;

	private String zhengwen;

	private String a1;

	private String a2;

	private String a3;

	private String a4;

	private String a5;

	// Constructors

	/** default constructor */
	public TbTechDiscoure() {
	}

	/** full constructor */
	public TbTechDiscoure(String pianming, String zuozhe1, String zuozhe2,
			String zuozhe3, String danwei, String kanming, Date fabiaoshijian,
			String qihao, String guanjianci, String zhaiyao, String zhengwen,
			String a1, String a2, String a3, String a4, String a5) {
		this.pianming = pianming;
		this.zuozhe1 = zuozhe1;
		this.zuozhe2 = zuozhe2;
		this.zuozhe3 = zuozhe3;
		this.danwei = danwei;
		this.kanming = kanming;
		this.fabiaoshijian = fabiaoshijian;
		this.qihao = qihao;
		this.guanjianci = guanjianci;
		this.zhaiyao = zhaiyao;
		this.zhengwen = zhengwen;
		this.a1 = a1;
		this.a2 = a2;
		this.a3 = a3;
		this.a4 = a4;
		this.a5 = a5;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPianming() {
		return this.pianming;
	}

	public void setPianming(String pianming) {
		this.pianming = pianming;
	}

	public String getZuozhe1() {
		return this.zuozhe1;
	}

	public void setZuozhe1(String zuozhe1) {
		this.zuozhe1 = zuozhe1;
	}

	public String getZuozhe2() {
		return this.zuozhe2;
	}

	public void setZuozhe2(String zuozhe2) {
		this.zuozhe2 = zuozhe2;
	}

	public String getZuozhe3() {
		return this.zuozhe3;
	}

	public void setZuozhe3(String zuozhe3) {
		this.zuozhe3 = zuozhe3;
	}

	public String getDanwei() {
		return this.danwei;
	}

	public void setDanwei(String danwei) {
		this.danwei = danwei;
	}

	public String getKanming() {
		return this.kanming;
	}

	public void setKanming(String kanming) {
		this.kanming = kanming;
	}

	public Date getFabiaoshijian() {
		return this.fabiaoshijian;
	}

	public void setFabiaoshijian(Date fabiaoshijian) {
		this.fabiaoshijian = fabiaoshijian;
	}

	public String getQihao() {
		return this.qihao;
	}

	public void setQihao(String qihao) {
		this.qihao = qihao;
	}

	public String getGuanjianci() {
		return this.guanjianci;
	}

	public void setGuanjianci(String guanjianci) {
		this.guanjianci = guanjianci;
	}

	public String getZhaiyao() {
		return this.zhaiyao;
	}

	public void setZhaiyao(String zhaiyao) {
		this.zhaiyao = zhaiyao;
	}

	public String getZhengwen() {
		return this.zhengwen;
	}

	public void setZhengwen(String zhengwen) {
		this.zhengwen = zhengwen;
	}

	public String getA1() {
		return this.a1;
	}

	public void setA1(String a1) {
		this.a1 = a1;
	}

	public String getA2() {
		return this.a2;
	}

	public void setA2(String a2) {
		this.a2 = a2;
	}

	public String getA3() {
		return this.a3;
	}

	public void setA3(String a3) {
		this.a3 = a3;
	}

	public String getA4() {
		return this.a4;
	}

	public void setA4(String a4) {
		this.a4 = a4;
	}

	public String getA5() {
		return this.a5;
	}

	public void setA5(String a5) {
		this.a5 = a5;
	}

}