/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baosight.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.baosight.dao.Test;
import com.baosight.dao.TestDAO;
import com.baosight.dao.TestId;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2008
 * 
 * XDoclet definition:
 * @struts.action path="/test" name="testForm" input="/form/test.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class TestAction extends BaseDispatchAction {
	/*
	 * Generated Methods
	 */
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
//	public ActionForward execute(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		DynaActionForm testForm = (DynaActionForm) form;
//		TestDAO testDao = this.testService.getDao();
//		System.out.println(testDao.findAll().size());
//		request.getParameter("action");
//		return mapping.findForward("success");
//	}
	
	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm testForm = (DynaActionForm) form;
		TestDAO testDao = this.testService.getDao();
		System.out.println(testDao.findAll().size());
		System.out.println(System.getProperty("file.encoding"));
		System.out.println(request.getCharacterEncoding());
		testDao.save(new Test(new TestId(testForm.getString("name"))));
		System.out.println(testDao.findAll().size());
		return mapping.findForward("success");
	}
}