package com.baosight.dao;



/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser  implements java.io.Serializable {


    // Fields    

     private TUserId id;


    // Constructors

    /** default constructor */
    public TUser() {
    }

    
    /** full constructor */
    public TUser(TUserId id) {
        this.id = id;
    }

   
    // Property accessors

    public TUserId getId() {
        return this.id;
    }
    
    public void setId(TUserId id) {
        this.id = id;
    }
   








}