/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.baosight.base.struts.action;


import java.io.IOException;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.baosight.mode.TbCommonality;
import com.baosight.mode.TbCommonalityComm;
import com.baosight.struts.action.BaseDispatchAction;

/**
 * MyEclipse Struts Creation date: 09-24-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/shortInfo" name="shortInfoForm"
 *                input="/WEB-INF/web/jsp/sendshortinfo/shortInfo.jsp"
 *                scope="request" validate="true"
 */
public class SmsSubscribeSelPeoAction extends BaseDispatchAction {
	/**
	 * 进入显示公共通讯录组页面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward inputCommSelPeo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("inputCommSelPeo");		
	}
	public ActionForward inputCommoGroup(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("inputCommoGroup");		
	}
	public ActionForward inputCommonality(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println(request.getParameter("id"));
		request.setAttribute("id", request.getParameter("id"));
		return mapping.findForward("inputCommonality");		
	}	
	/**
	 * 显示公共通讯录组页面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward showCommonGroupTree(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		String id = request.getParameter("cid");
		StringBuffer xml = new StringBuffer();
		//Map funList = functionMgr.findFunByRid(rid);
		List list = this.commonalityCommMgr.findAllForSubscribeTree(id);
		Iterator iterator = list.iterator();

		xml.append("<?xml version=\"1.0\" encoding=\"GBK\"?>");
		xml.append("<CommonGroups>\r\n");
		xml.append("<isFirst>");
		xml.append("<first>" + "false" + "</first>");
		xml.append("</isFirst>");
		while (iterator.hasNext()) {
			xml.append("<commongroup>\r\n");
			TbCommonalityComm instance = (TbCommonalityComm) iterator.next();
			xml.append("<id>" + instance.getId() + "</id>\r\n");
			xml.append("<title>" + instance.getName() + "</title>\r\n");
			xml.append("<parId>" + instance.getParentId() + "</parId>\r\n");
			xml.append("<insure>" + instance.getInuse() + "</insure>\r\n");
			xml.append("</commongroup>\r\n");
		}
		xml.append("</CommonGroups>");
		response.setHeader("Pragma", "No-cache");
		response.setHeader("Cache-Control", "no-cache");
		response.setDateHeader("Expires", 0);
		response.setContentType("text/xml;charset=GBK");
		System.out.println("------------" + xml.toString());
		try {
			response.getWriter().print(xml);
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}	
	public ActionForward showCommonalityTree(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		String id = request.getParameter("id");
		StringBuffer xml = new StringBuffer();
		List list = this.commonalityMgr.findByCommId(id);
		Iterator iterator = list.iterator();

		xml.append("<?xml version=\"1.0\" encoding=\"GBK\"?>");
		xml.append("<Commonalitys>\r\n");
		xml.append("<isFirst>");
		xml.append("<first>" + "false" + "</first>");
		xml.append("</isFirst>");
		while (iterator.hasNext()) {
			xml.append("<commonality>\r\n");
			TbCommonality instance = (TbCommonality) iterator.next();
			xml.append("<id>" + instance.getId() + "</id>\r\n");
			xml.append("<title>" + instance.getName() + "</title>\r\n");
			xml.append("</commonality>\r\n");
		}
		xml.append("</Commonalitys>");
		response.setHeader("Pragma", "No-cache");
		response.setHeader("Cache-Control", "no-cache");
		response.setDateHeader("Expires", 0);
		response.setContentType("text/xml;charset=GBK");
		System.out.println("------------" + xml.toString());
		try {
			response.getWriter().print(xml);
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}	


}