package com.baosight.mode;

import java.util.Date;

/**
 * AbstractTFileAllZf generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTFileAllZf implements java.io.Serializable {

	// Fields

	private Long fileid;

	private String title;

	private Date createtime;

	private Date starttime;

	private Date endtime;

	private String author;

	private Long typeid;

	private Long folderid;

	private String purview;

	private String isvalid;

	private Long keyword1;

	private Long keyword2;

	private Long keyword3;

	private Long keyword4;

	private Long temp;

	private Long hit;

	private Long inputuer;

	private Long deptid;

	private Long infotype;

	private String filenumber;

	private Long issueddept1;

	private String issueddept2;

	private Long carriertype;

	private String getid;

	private String keyword5;

	private Long lsh;

	private Long auditing;

	private String reason;

	// Constructors

	/** default constructor */
	public AbstractTFileAllZf() {
	}

	/** minimal constructor */
	public AbstractTFileAllZf(String title, Date createtime, Long typeid,
			Long folderid) {
		this.title = title;
		this.createtime = createtime;
		this.typeid = typeid;
		this.folderid = folderid;
	}

	/** full constructor */
	public AbstractTFileAllZf(String title, Date createtime, Date starttime,
			Date endtime, String author, Long typeid, Long folderid,
			String purview, String isvalid, Long keyword1, Long keyword2,
			Long keyword3, Long keyword4, Long temp, Long hit, Long inputuer,
			Long deptid, Long infotype, String filenumber, Long issueddept1,
			String issueddept2, Long carriertype, String getid,
			String keyword5, Long lsh, Long auditing, String reason) {
		this.title = title;
		this.createtime = createtime;
		this.starttime = starttime;
		this.endtime = endtime;
		this.author = author;
		this.typeid = typeid;
		this.folderid = folderid;
		this.purview = purview;
		this.isvalid = isvalid;
		this.keyword1 = keyword1;
		this.keyword2 = keyword2;
		this.keyword3 = keyword3;
		this.keyword4 = keyword4;
		this.temp = temp;
		this.hit = hit;
		this.inputuer = inputuer;
		this.deptid = deptid;
		this.infotype = infotype;
		this.filenumber = filenumber;
		this.issueddept1 = issueddept1;
		this.issueddept2 = issueddept2;
		this.carriertype = carriertype;
		this.getid = getid;
		this.keyword5 = keyword5;
		this.lsh = lsh;
		this.auditing = auditing;
		this.reason = reason;
	}

	// Property accessors

	public Long getFileid() {
		return this.fileid;
	}

	public void setFileid(Long fileid) {
		this.fileid = fileid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Long getTypeid() {
		return this.typeid;
	}

	public void setTypeid(Long typeid) {
		this.typeid = typeid;
	}

	public Long getFolderid() {
		return this.folderid;
	}

	public void setFolderid(Long folderid) {
		this.folderid = folderid;
	}

	public String getPurview() {
		return this.purview;
	}

	public void setPurview(String purview) {
		this.purview = purview;
	}

	public String getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(String isvalid) {
		this.isvalid = isvalid;
	}

	public Long getKeyword1() {
		return this.keyword1;
	}

	public void setKeyword1(Long keyword1) {
		this.keyword1 = keyword1;
	}

	public Long getKeyword2() {
		return this.keyword2;
	}

	public void setKeyword2(Long keyword2) {
		this.keyword2 = keyword2;
	}

	public Long getKeyword3() {
		return this.keyword3;
	}

	public void setKeyword3(Long keyword3) {
		this.keyword3 = keyword3;
	}

	public Long getKeyword4() {
		return this.keyword4;
	}

	public void setKeyword4(Long keyword4) {
		this.keyword4 = keyword4;
	}

	public Long getTemp() {
		return this.temp;
	}

	public void setTemp(Long temp) {
		this.temp = temp;
	}

	public Long getHit() {
		return this.hit;
	}

	public void setHit(Long hit) {
		this.hit = hit;
	}

	public Long getInputuer() {
		return this.inputuer;
	}

	public void setInputuer(Long inputuer) {
		this.inputuer = inputuer;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public Long getInfotype() {
		return this.infotype;
	}

	public void setInfotype(Long infotype) {
		this.infotype = infotype;
	}

	public String getFilenumber() {
		return this.filenumber;
	}

	public void setFilenumber(String filenumber) {
		this.filenumber = filenumber;
	}

	public Long getIssueddept1() {
		return this.issueddept1;
	}

	public void setIssueddept1(Long issueddept1) {
		this.issueddept1 = issueddept1;
	}

	public String getIssueddept2() {
		return this.issueddept2;
	}

	public void setIssueddept2(String issueddept2) {
		this.issueddept2 = issueddept2;
	}

	public Long getCarriertype() {
		return this.carriertype;
	}

	public void setCarriertype(Long carriertype) {
		this.carriertype = carriertype;
	}

	public String getGetid() {
		return this.getid;
	}

	public void setGetid(String getid) {
		this.getid = getid;
	}

	public String getKeyword5() {
		return this.keyword5;
	}

	public void setKeyword5(String keyword5) {
		this.keyword5 = keyword5;
	}

	public Long getLsh() {
		return this.lsh;
	}

	public void setLsh(Long lsh) {
		this.lsh = lsh;
	}

	public Long getAuditing() {
		return this.auditing;
	}

	public void setAuditing(Long auditing) {
		this.auditing = auditing;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}