package com.baosight.mode;

import java.util.Date;

/**
 * Stufflisting generated by MyEclipse Persistence Tools
 */

public class Stufflisting implements java.io.Serializable {

	// Fields

	private String id;

	private String type;

	private String name;

	private String remark;

	private Long num;

	private Long totalnum;

	private String status;

	private String upload;

	private Date uploadtime;

	private String applyid;

	private String standby1;

	private String standby2;

	private String standby3;

	private String standby4;

	// Constructors

	/** default constructor */
	public Stufflisting() {
	}

	/** full constructor */
	public Stufflisting(String type, String name, String remark, Long num,
			Long totalnum, String status, String upload, Date uploadtime,
			String applyid, String standby1, String standby2, String standby3,
			String standby4) {
		this.type = type;
		this.name = name;
		this.remark = remark;
		this.num = num;
		this.totalnum = totalnum;
		this.status = status;
		this.upload = upload;
		this.uploadtime = uploadtime;
		this.applyid = applyid;
		this.standby1 = standby1;
		this.standby2 = standby2;
		this.standby3 = standby3;
		this.standby4 = standby4;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Long getNum() {
		return this.num;
	}

	public void setNum(Long num) {
		this.num = num;
	}

	public Long getTotalnum() {
		return this.totalnum;
	}

	public void setTotalnum(Long totalnum) {
		this.totalnum = totalnum;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUpload() {
		return this.upload;
	}

	public void setUpload(String upload) {
		this.upload = upload;
	}

	public Date getUploadtime() {
		return this.uploadtime;
	}

	public void setUploadtime(Date uploadtime) {
		this.uploadtime = uploadtime;
	}

	public String getApplyid() {
		return this.applyid;
	}

	public void setApplyid(String applyid) {
		this.applyid = applyid;
	}

	public String getStandby1() {
		return this.standby1;
	}

	public void setStandby1(String standby1) {
		this.standby1 = standby1;
	}

	public String getStandby2() {
		return this.standby2;
	}

	public void setStandby2(String standby2) {
		this.standby2 = standby2;
	}

	public String getStandby3() {
		return this.standby3;
	}

	public void setStandby3(String standby3) {
		this.standby3 = standby3;
	}

	public String getStandby4() {
		return this.standby4;
	}

	public void setStandby4(String standby4) {
		this.standby4 = standby4;
	}

}