package com.baosight.mode;

import java.util.Date;

/**
 * TbApply generated by MyEclipse Persistence Tools
 */

public class TbApply implements java.io.Serializable {

	// Fields

	private String id;

	//受理号
	private String applyNo;

	//受理日期
	private Date applyDate;

	//所属行业
	private String trade;

	//受理类别
	private String acceptType;

	//受理事项
	private String acceptName;

	//受理事项编号
	private String acceptNo;

	//项目名称
	private String projectName;

	//项目地址
	private String projectAddress;

	//受理时限
	private Long dueWorkDay;

	//拟办结日期
	private Date planEndDate;

	//实际办结日期
	private Date actEndDate;

	//申请内容
	private String applyContent;

	//具体内容
	private String certNo;

	//许可证编号
	private String status;

	//状态：办理中|办理完毕|取消
	private String applyPerson;

	//申请人
	private String legual;

	//申请人地址
	private String applyAddress;

	//申请人邮编
	private String applyZipCode;

	//联系人
	private String contractPerson;

	//联系人电话
	private String contractPhone;

	//联系人传真
	private String contractFax;

	//联系人手机
	private String contractMobile;

	//流程实例ID
	private String instanceId;

	//流程模型ID
	private String modelId;

	private String processId;

	private Date createDate;

	private String createUser;

	private String updateUser;

	private Date updateDate;

	//审批状态
	private String cert_Status;

	//节点状态
	private String dealStatus;

	//经办人
	private String dealPerson;

	//审批日期
	private Date dealDate;

	//备注
	private String remark;

	private String attr1;

	private String attr2;

	private String attr3;

	//领取日期
	private Date drawDate;

	//申请日期
	private String requestDate;

	//额外材料备注
	private String remark2;

	//申请人注册ID
	private Integer userId;

	//预处理号
	private String presellno;

	//是否短信发送(1表示发送)
	private Long ismis;

	//是否审批完毕
	private Long isover;

	//单位性质
	private Long comType;

	//审核通过的邮件内容
	private String emailcontentok;

	//审核不通过的邮件内容
	private String emailcontentno;

	// Constructors

	/** default constructor */
	public TbApply() {
	}

	public TbApply(String applyNo, Date applyDate,
			String trade, String acceptType, String acceptName,
			String acceptNo, String projectName, String projectAddress,
			Long dueWorkDay, Date planEndDate, Date actEndDate,
			String applyContent, String certNo, String status,
			String applyPerson, String legual, String applyAddress,
			String applyZipCode, String contractPerson, String contractPhone,
			String contractFax, String contractMobile, String instanceId,
			String modelId, String processId, Date createDate,
			String createUser, String updateUser, Date updateDate,
			String cert_Status, String dealStatus, String dealPerson,
			Date dealDate, String remark, String attr1,
			String attr2, String attr3, Date drawDate, 
			String requestDate, String remark2, Integer userId, 
			String presellno, Long ismis, Long isover, Long comType, 
			String emailcontentok, String emailcontentno) {
		this.applyNo = applyNo;
		this.applyDate = applyDate;
		this.trade = trade;
		this.acceptType = acceptType;
		this.acceptName = acceptName;
		this.acceptNo = acceptNo;
		this.projectName = projectName;
		this.projectAddress = projectAddress;
		this.dueWorkDay = dueWorkDay;
		this.planEndDate = planEndDate;
		this.actEndDate = actEndDate;
		this.applyContent = applyContent;
		this.certNo = certNo;
		this.status = status;
		this.applyPerson = applyPerson;
		this.legual = legual;
		this.applyAddress = applyAddress;
		this.applyZipCode = applyZipCode;
		this.contractPerson = contractPerson;
		this.contractPhone = contractPhone;
		this.contractFax = contractFax;
		this.contractMobile = contractMobile;
		this.instanceId = instanceId;
		this.modelId = modelId;
		this.processId = processId;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
		this.cert_Status = cert_Status;
		this.dealStatus = dealStatus;
		this.dealPerson = dealPerson;
		this.dealDate = dealDate;
		this.remark = remark;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.drawDate = drawDate;
		this.requestDate = requestDate;
		this.remark2 = remark2;
		this.userId = userId;
		this.presellno = presellno;
		this.ismis = ismis;
		this.isover = isover;
		this.comType = comType;
		this.emailcontentok = emailcontentok;
		this.emailcontentno = emailcontentno;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAcceptName() {
		return acceptName;
	}

	public void setAcceptName(String acceptName) {
		this.acceptName = acceptName;
	}

	public String getAcceptNo() {
		return acceptNo;
	}

	public void setAcceptNo(String acceptNo) {
		this.acceptNo = acceptNo;
	}

	public String getAcceptType() {
		return acceptType;
	}

	public void setAcceptType(String acceptType) {
		this.acceptType = acceptType;
	}

	public Date getActEndDate() {
		return actEndDate;
	}

	public void setActEndDate(Date actEndDate) {
		this.actEndDate = actEndDate;
	}

	public String getApplyAddress() {
		return applyAddress;
	}

	public void setApplyAddress(String applyAddress) {
		this.applyAddress = applyAddress;
	}

	public String getApplyContent() {
		return applyContent;
	}

	public void setApplyContent(String applyContent) {
		this.applyContent = applyContent;
	}

	public Date getApplyDate() {
		return applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getApplyNo() {
		return applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	public String getApplyPerson() {
		return applyPerson;
	}

	public void setApplyPerson(String applyPerson) {
		this.applyPerson = applyPerson;
	}

	public String getApplyZipCode() {
		return applyZipCode;
	}

	public void setApplyZipCode(String applyZipCode) {
		this.applyZipCode = applyZipCode;
	}

	public String getAttr1() {
		return attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getCert_Status() {
		return cert_Status;
	}

	public void setCert_Status(String cert_Status) {
		this.cert_Status = cert_Status;
	}

	public String getCertNo() {
		return certNo;
	}

	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

	public Long getComType() {
		return comType;
	}

	public void setComType(Long comType) {
		this.comType = comType;
	}

	public String getContractFax() {
		return contractFax;
	}

	public void setContractFax(String contractFax) {
		this.contractFax = contractFax;
	}

	public String getContractMobile() {
		return contractMobile;
	}

	public void setContractMobile(String contractMobile) {
		this.contractMobile = contractMobile;
	}

	public String getContractPerson() {
		return contractPerson;
	}

	public void setContractPerson(String contractPerson) {
		this.contractPerson = contractPerson;
	}

	public String getContractPhone() {
		return contractPhone;
	}

	public void setContractPhone(String contractPhone) {
		this.contractPhone = contractPhone;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getDealDate() {
		return dealDate;
	}

	public void setDealDate(Date dealDate) {
		this.dealDate = dealDate;
	}

	public String getDealPerson() {
		return dealPerson;
	}

	public void setDealPerson(String dealPerson) {
		this.dealPerson = dealPerson;
	}

	public String getDealStatus() {
		return dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public Date getDrawDate() {
		return drawDate;
	}

	public void setDrawDate(Date drawDate) {
		this.drawDate = drawDate;
	}

	public Long getDueWorkDay() {
		return dueWorkDay;
	}

	public void setDueWorkDay(Long dueWorkDay) {
		this.dueWorkDay = dueWorkDay;
	}

	public String getEmailcontentno() {
		return emailcontentno;
	}

	public void setEmailcontentno(String emailcontentno) {
		this.emailcontentno = emailcontentno;
	}

	public String getEmailcontentok() {
		return emailcontentok;
	}

	public void setEmailcontentok(String emailcontentok) {
		this.emailcontentok = emailcontentok;
	}

	public String getInstanceId() {
		return instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public Long getIsmis() {
		return ismis;
	}

	public void setIsmis(Long ismis) {
		this.ismis = ismis;
	}

	public Long getIsover() {
		return isover;
	}

	public void setIsover(Long isover) {
		this.isover = isover;
	}

	public String getLegual() {
		return legual;
	}

	public void setLegual(String legual) {
		this.legual = legual;
	}

	public String getModelId() {
		return modelId;
	}

	public void setModelId(String modelId) {
		this.modelId = modelId;
	}

	public Date getPlanEndDate() {
		return planEndDate;
	}

	public void setPlanEndDate(Date planEndDate) {
		this.planEndDate = planEndDate;
	}

	public String getPresellno() {
		return presellno;
	}

	public void setPresellno(String presellno) {
		this.presellno = presellno;
	}

	public String getProcessId() {
		return processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getProjectAddress() {
		return projectAddress;
	}

	public void setProjectAddress(String projectAddress) {
		this.projectAddress = projectAddress;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemark2() {
		return remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public String getRequestDate() {
		return requestDate;
	}

	public void setRequestDate(String requestDate) {
		this.requestDate = requestDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTrade() {
		return trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}