package com.baosight.mode;

/**
 * TbAuthInfo generated by MyEclipse Persistence Tools
 */

public class TbAuthInfo implements java.io.Serializable {

	// Fields

	private String id;

	private String funid;

	private String name;

	private String hasChild;

	private String righttypeid;

	private String rem;

	// Constructors

	/** default constructor */
	public TbAuthInfo() {
	}

	/** full constructor */
	public TbAuthInfo(String funid, String name, String hasChild,
			String righttypeid, String rem) {
		this.funid = funid;
		this.name = name;
		this.hasChild = hasChild;
		this.righttypeid = righttypeid;
		this.rem = rem;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFunid() {
		return this.funid;
	}

	public void setFunid(String funid) {
		this.funid = funid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(String hasChild) {
		this.hasChild = hasChild;
	}

	public String getRighttypeid() {
		return this.righttypeid;
	}

	public void setRighttypeid(String righttypeid) {
		this.righttypeid = righttypeid;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

}