package com.baosight.mode;

import java.util.Date;

/**
 * TbCommission generated by MyEclipse Persistence Tools
 */

public class TbCommission implements java.io.Serializable {

	// Fields

	private String id;
	
	private String commTitle;

	private String commId;

	private String commName;

	private String becommedId;

	private String becommedName;

	private Date begintime;

	private Date endtime;

	private String commMatters;

	private Long commFlag;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbCommission() {
	}

	/** full constructor */
	public TbCommission(String commTitle,String commId, String commName, String becommedId,
			String becommedName, Date begintime, Date endtime,
			String commMatters, Long commFlag, String attr1, String attr2,
			String attr3) {
		this.commTitle = commTitle;
		this.commId = commId;
		this.commName = commName;
		this.becommedId = becommedId;
		this.becommedName = becommedName;
		this.begintime = begintime;
		this.endtime = endtime;
		this.commMatters = commMatters;
		this.commFlag = commFlag;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCommId() {
		return this.commId;
	}

	public void setCommId(String commId) {
		this.commId = commId;
	}

	public String getCommName() {
		return this.commName;
	}

	public void setCommName(String commName) {
		this.commName = commName;
	}

	public String getBecommedId() {
		return this.becommedId;
	}

	public void setBecommedId(String becommedId) {
		this.becommedId = becommedId;
	}

	public String getBecommedName() {
		return this.becommedName;
	}

	public void setBecommedName(String becommedName) {
		this.becommedName = becommedName;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getCommMatters() {
		return this.commMatters;
	}

	public void setCommMatters(String commMatters) {
		this.commMatters = commMatters;
	}

	public Long getCommFlag() {
		return this.commFlag;
	}

	public void setCommFlag(Long commFlag) {
		this.commFlag = commFlag;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getCommTitle() {
		return commTitle;
	}

	public void setCommTitle(String commTitle) {
		this.commTitle = commTitle;
	}

}