package com.baosight.mode;

/**
 * TbCommonalityComm generated by MyEclipse Persistence Tools
 */

public class TbCommonalityComm implements java.io.Serializable {

	// Fields

	private String id;

	private String parentId;

	private String name;

	private Long inuse;

	private String belong;

	private String remark;

	private String attr1;

	private String attr2;

	private String attr3;

	private String attr4;

	private String attr5;

	private Integer node;
	// Constructors

	/** default constructor */
	public TbCommonalityComm() {
	}
	
	public TbCommonalityComm(String parentId, String name, Long inuse,String belong,
			String remark,String attr1) {
		this.parentId = parentId;
		this.name = name;
		this.inuse = inuse;
		this.belong=belong;
		this.remark = remark;
		this.attr1 = attr1;
	}

	/** full constructor */
	public TbCommonalityComm(String parentId, String name, Long inuse,
			String belong, String remark, String attr1, String attr2,
			String attr3, String attr4, String attr5) {
		this.parentId = parentId;
		this.name = name;
		this.inuse = inuse;
		this.belong = belong;
		this.remark = remark;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.attr5 = attr5;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getInuse() {
		return this.inuse;
	}

	public void setInuse(Long inuse) {
		this.inuse = inuse;
	}

	public String getBelong() {
		return this.belong;
	}

	public void setBelong(String belong) {
		this.belong = belong;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	public String getAttr5() {
		return this.attr5;
	}

	public void setAttr5(String attr5) {
		this.attr5 = attr5;
	}

	public Integer getNode() {
		return node;
	}

	public void setNode(Integer node) {
		this.node = node;
	}

}