package com.baosight.mode;

/**
 * TbDept generated by MyEclipse Persistence Tools
 */

public class TbDept implements java.io.Serializable {

	// Fields

	private String id;

	private String code;

	private String name;

	private String lvl;

	private String parCode;

	private String tel;

	private String ctc;

	private String rem;

	private Long defOrder;

	private String userDept;

	private Integer node;

	// Constructors

	/**
	 * @return the userDept
	 */
	public String getUserDept() {
		return userDept;
	}

	/**
	 * @param userDept
	 *            the userDept to set
	 */
	public void setUserDept(String userDept) {
		this.userDept = userDept;
	}

	/** default constructor */
	public TbDept() {
	}

	/** minimal constructor */
	public TbDept(String code, String name) {
		this.code = code;
		this.name = name;
	}

	/** full constructor */
	public TbDept(String code, String name, String lvl, String parCode,
			String tel, String ctc, String rem, Long defOrder, String userDept) {
		this.code = code;
		this.name = name;
		this.lvl = lvl;
		this.parCode = parCode;
		this.tel = tel;
		this.ctc = ctc;
		this.rem = rem;
		this.defOrder = defOrder;
		this.userDept = userDept;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvl() {
		return this.lvl;
	}

	public void setLvl(String lvl) {
		this.lvl = lvl;
	}

	public String getParCode() {
		return this.parCode;
	}

	public void setParCode(String parCode) {
		this.parCode = parCode;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getCtc() {
		return this.ctc;
	}

	public void setCtc(String ctc) {
		this.ctc = ctc;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public Long getDefOrder() {
		return this.defOrder;
	}

	public void setDefOrder(Long defOrder) {
		this.defOrder = defOrder;
	}

	public Integer getNode() {
		return node;
	}

	public void setNode(Integer node) {
		this.node = node;
	}

	public TbDept(String id, String code, String name, String lvl,
			String parCode, String tel, String ctc, String rem, Long defOrder,
			String userDept, Integer node) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.lvl = lvl;
		this.parCode = parCode;
		this.tel = tel;
		this.ctc = ctc;
		this.rem = rem;
		this.defOrder = defOrder;
		this.userDept = userDept;
		this.node = node;
	}

}