package com.baosight.mode;

import java.util.Date;

/**
 * TbDocControl generated by MyEclipse Persistence Tools
 */

public class TbDocControl implements java.io.Serializable {

	// Fields

	private String id;

	private TbDocRec tbDocRec;

	private String stateName;

	private Date createTime;

	private Date inputTime;

	private Date closeTime;

	private String userId;

	private String userName;

	private String state;

	private String stateType = "0";

	// Constructors

	/** default constructor */
	public TbDocControl() {
	}

	/** full constructor */
	public TbDocControl(TbDocRec tbDocRec, String stateName, Date createTime,
			Date inputTime, Date closeTime, String userId, String userName,
			String state, String stateType) {
		this.tbDocRec = tbDocRec;
		this.stateName = stateName;
		this.createTime = createTime;
		this.inputTime = inputTime;
		this.closeTime = closeTime;
		this.userId = userId;
		this.userName = userName;
		this.state = state;
		this.stateType = stateType;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbDocRec getTbDocRec() {
		return this.tbDocRec;
	}

	public void setTbDocRec(TbDocRec tbDocRec) {
		this.tbDocRec = tbDocRec;
	}

	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getStateType() {
		return this.stateType;
	}

	public void setStateType(String stateType) {
		this.stateType = stateType;
	}

}