package com.baosight.mode;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbDocSend generated by MyEclipse Persistence Tools
 */

public class TbDocSend implements java.io.Serializable {

	// Fields

	private String id;

	private String fileSecret;

	private String sign;

	private String draftOpinion;

	private String fileTitle;

	private String fileDept;

	private String sendMain;

	private String sendSecond;

	private String topicWord;

	private String mainDraftUser;

	private String mainChargeUser;

	private String officeDraftUser;

	private String officeChargeUser;

	private String fileNo;

	private Long fileNum;

	private String printUser;

	private String collateUser;

	private Date fileDate;

	private String signOpinion;

	private String secret1;

	private String secret2;

	private Long filePages;

	private String sendFileType;

	private String docState;

	private String mainSignDept;

	private String fileType;

	private Set tbDocsendControls = new HashSet(0);

	// Constructors

	/** default constructor */
	public TbDocSend() {
	}

	/** full constructor */
	public TbDocSend(String fileSecret, String sign, String draftOpinion,
			String fileTitle, String fileDept, String sendMain,
			String sendSecond, String topicWord, String mainDraftUser,
			String mainChargeUser, String officeDraftUser,
			String officeChargeUser, String fileNo, Long fileNum,
			String printUser, String collateUser, Date fileDate,
			String signOpinion, String secret1, String secret2, Long filePages,
			String sendFileType, String docState, String mainSignDept,
			String fileType, Set tbDocsendControls) {
		this.fileSecret = fileSecret;
		this.sign = sign;
		this.draftOpinion = draftOpinion;
		this.fileTitle = fileTitle;
		this.fileDept = fileDept;
		this.sendMain = sendMain;
		this.sendSecond = sendSecond;
		this.topicWord = topicWord;
		this.mainDraftUser = mainDraftUser;
		this.mainChargeUser = mainChargeUser;
		this.officeDraftUser = officeDraftUser;
		this.officeChargeUser = officeChargeUser;
		this.fileNo = fileNo;
		this.fileNum = fileNum;
		this.printUser = printUser;
		this.collateUser = collateUser;
		this.fileDate = fileDate;
		this.signOpinion = signOpinion;
		this.secret1 = secret1;
		this.secret2 = secret2;
		this.filePages = filePages;
		this.sendFileType = sendFileType;
		this.docState = docState;
		this.mainSignDept = mainSignDept;
		this.fileType = fileType;
		this.tbDocsendControls = tbDocsendControls;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileSecret() {
		return this.fileSecret;
	}

	public void setFileSecret(String fileSecret) {
		this.fileSecret = fileSecret;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getDraftOpinion() {
		return this.draftOpinion;
	}

	public void setDraftOpinion(String draftOpinion) {
		this.draftOpinion = draftOpinion;
	}

	public String getFileTitle() {
		return this.fileTitle;
	}

	public void setFileTitle(String fileTitle) {
		this.fileTitle = fileTitle;
	}

	public String getFileDept() {
		return this.fileDept;
	}

	public void setFileDept(String fileDept) {
		this.fileDept = fileDept;
	}

	public String getSendMain() {
		return this.sendMain;
	}

	public void setSendMain(String sendMain) {
		this.sendMain = sendMain;
	}

	public String getSendSecond() {
		return this.sendSecond;
	}

	public void setSendSecond(String sendSecond) {
		this.sendSecond = sendSecond;
	}

	public String getTopicWord() {
		return this.topicWord;
	}

	public void setTopicWord(String topicWord) {
		this.topicWord = topicWord;
	}

	public String getMainDraftUser() {
		return this.mainDraftUser;
	}

	public void setMainDraftUser(String mainDraftUser) {
		this.mainDraftUser = mainDraftUser;
	}

	public String getMainChargeUser() {
		return this.mainChargeUser;
	}

	public void setMainChargeUser(String mainChargeUser) {
		this.mainChargeUser = mainChargeUser;
	}

	public String getOfficeDraftUser() {
		return this.officeDraftUser;
	}

	public void setOfficeDraftUser(String officeDraftUser) {
		this.officeDraftUser = officeDraftUser;
	}

	public String getOfficeChargeUser() {
		return this.officeChargeUser;
	}

	public void setOfficeChargeUser(String officeChargeUser) {
		this.officeChargeUser = officeChargeUser;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public Long getFileNum() {
		return this.fileNum;
	}

	public void setFileNum(Long fileNum) {
		this.fileNum = fileNum;
	}

	public String getPrintUser() {
		return this.printUser;
	}

	public void setPrintUser(String printUser) {
		this.printUser = printUser;
	}

	public String getCollateUser() {
		return this.collateUser;
	}

	public void setCollateUser(String collateUser) {
		this.collateUser = collateUser;
	}

	public Date getFileDate() {
		return this.fileDate;
	}

	public void setFileDate(Date fileDate) {
		this.fileDate = fileDate;
	}

	public String getSignOpinion() {
		return this.signOpinion;
	}

	public void setSignOpinion(String signOpinion) {
		this.signOpinion = signOpinion;
	}

	public String getSecret1() {
		return this.secret1;
	}

	public void setSecret1(String secret1) {
		this.secret1 = secret1;
	}

	public String getSecret2() {
		return this.secret2;
	}

	public void setSecret2(String secret2) {
		this.secret2 = secret2;
	}

	public Long getFilePages() {
		return this.filePages;
	}

	public void setFilePages(Long filePages) {
		this.filePages = filePages;
	}

	public String getSendFileType() {
		return this.sendFileType;
	}

	public void setSendFileType(String sendFileType) {
		this.sendFileType = sendFileType;
	}

	public String getDocState() {
		return this.docState;
	}

	public void setDocState(String docState) {
		this.docState = docState;
	}

	public String getMainSignDept() {
		return this.mainSignDept;
	}

	public void setMainSignDept(String mainSignDept) {
		this.mainSignDept = mainSignDept;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Set getTbDocsendControls() {
		return this.tbDocsendControls;
	}

	public void setTbDocsendControls(Set tbDocsendControls) {
		this.tbDocsendControls = tbDocsendControls;
	}

}