package com.baosight.mode;

/**
 * TbDocsendListitems generated by MyEclipse Persistence Tools
 */

public class TbDocsendListitems implements java.io.Serializable {

	// Fields

	private String id;

	private Long style;

	private Long code;

	private String title;

	private String info;

	// Constructors

	/** default constructor */
	public TbDocsendListitems() {
	}

	/** minimal constructor */
	public TbDocsendListitems(Long code, String title) {
		this.code = code;
		this.title = title;
	}

	/** full constructor */
	public TbDocsendListitems(Long style, Long code, String title, String info) {
		this.style = style;
		this.code = code;
		this.title = title;
		this.info = info;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getStyle() {
		return this.style;
	}

	public void setStyle(Long style) {
		this.style = style;
	}

	public Long getCode() {
		return this.code;
	}

	public void setCode(Long code) {
		this.code = code;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}