package com.baosight.mode;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.sql.Clob;
/**
 * TbFilesend generated by MyEclipse Persistence Tools
 */

public class TbFilesend implements java.io.Serializable {

	// Fields

	private String id;

	private String senderId;

	private Clob  receiverId;

	private Clob ccId;

	private Clob  stId;

	private String subject;

	private String content;

	private Date sendDt;

	private Long sendType;

	private String isView;
	
	private Set tbFilesendAttachments = new HashSet(0);

	// Constructors

	/** default constructor */
	public TbFilesend() {
	}

	/** full constructor */
	public TbFilesend(String senderId, Clob receiverId, Clob ccId,
			Clob stId, String subject, String content, Date sendDt,
			Long sendType, Set tbFilesendAttachments) {
		this.senderId = senderId;
		this.receiverId = receiverId;
		this.ccId = ccId;
		this.stId = stId;
		this.subject = subject;
		this.content = content;
		this.sendDt = sendDt;
		this.sendType = sendType;
		this.tbFilesendAttachments = tbFilesendAttachments;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	public Clob getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(Clob receiverId) {
		this.receiverId = receiverId;
	}

	public Clob getCcId() {
		return this.ccId;
	}

	public void setCcId(Clob ccId) {
		this.ccId = ccId;
	}

	public Clob getStId() {
		return this.stId;
	}

	public void setStId(Clob stId) {
		this.stId = stId;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendDt() {
		return this.sendDt;
	}

	public void setSendDt(Date sendDt) {
		this.sendDt = sendDt;
	}

	public Long getSendType() {
		return this.sendType;
	}

	public void setSendType(Long sendType) {
		this.sendType = sendType;
	}

	public Set getTbFilesendAttachments() {
		return this.tbFilesendAttachments;
	}

	public void setTbFilesendAttachments(Set tbFilesendAttachments) {
		this.tbFilesendAttachments = tbFilesendAttachments;
	}

	public String getIsView() {
		return isView;
	}

	public void setIsView(String isView) {
		this.isView = isView;
	}

}