package com.baosight.mode;

/**
 * TbFunction generated by MyEclipse Persistence Tools
 */

public class TbFunction implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String funKey;

	private String sysId;

	private String parId;

	private Long inuse;

	private Long deforder;

	private String nodetype;

	private Integer node;

	private String righttypeid;

	private String url;

	private String defor;
	
	private String imageName;

	private String needKey;

	/**
	 * @return the defor
	 */
	public String getDefor() {
		return defor;
	}

	/**
	 * @param defor
	 *            the defor to set
	 */
	public void setDefor(String defor) {
		this.defor = defor;
	}

	public TbFunction(String id, String name, String funKey, String sysId,
			String parId, Long inuse, Long deforder, String nodetype,
			Integer node, String righttypeid, String url, String defor,String needKey) {
		this.id = id;
		this.name = name;
		this.funKey = funKey;
		this.sysId = sysId;
		this.parId = parId;
		this.inuse = inuse;
		this.deforder = deforder;
		this.nodetype = nodetype;
		this.node = node;
		this.righttypeid = righttypeid;
		this.url = url;
		this.defor = defor;
		this.needKey = needKey;
	}

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFunKey() {
		return this.funKey;
	}

	public void setFunKey(String funKey) {
		this.funKey = funKey;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public String getParId() {
		return this.parId;
	}

	public void setParId(String parId) {
		this.parId = parId;
	}

	public Long getInuse() {
		return this.inuse;
	}

	public void setInuse(Long inuse) {
		this.inuse = inuse;
	}

	public Long getDeforder() {
		return this.deforder;
	}

	public void setDeforder(Long deforder) {
		this.deforder = deforder;
	}

	public String getNodetype() {
		return this.nodetype;
	}

	public void setNodetype(String nodetype) {
		this.nodetype = nodetype;
	}

	public Integer getNode() {
		return node;
	}

	public void setNode(Integer node) {
		this.node = node;
	}

	public String getRighttypeid() {
		return righttypeid;
	}

	public void setRighttypeid(String righttypeid) {
		this.righttypeid = righttypeid;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	// Constructors
	/** full constructor */

	/** default constructor */
	public TbFunction() {
	}

	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public String getNeedKey() {
		return needKey;
	}

	public void setNeedKey(String needKey) {
		this.needKey = needKey;
	}

}