package com.baosight.mode;

import java.sql.Clob;
import java.util.Date;


/**
 * TbGovInfoPubContent generated by MyEclipse Persistence Tools
 */

public class TbGovInfoPubContent  implements java.io.Serializable {


    // Fields    

     private String fileId;
     private String infoSource;
     private String title;
     private String authorName;
     private String keyword;
     private String summary;
     private Clob content;
     private Date createTime;
     private String publishType;
     private String fileCode;
     private String infoSubject;
     private String offerWay;
     private String applyId;
     private Long status;
     private String attr1;
     private String attr2;
     private String attr3;
     private Long sendTo;
     private String lshType;


    // Constructors

    /** default constructor */
    public TbGovInfoPubContent() {
    }

    
    /** full constructor */
    public TbGovInfoPubContent(String infoSource, String title, String authorName, String keyword, String summary, Clob content, Date createTime, String publishType, String fileCode, String infoSubject, String offerWay, String applyId, Long status, String attr1, String attr2, String attr3, Long sendTo,String lshType) {
        this.infoSource = infoSource;
        this.title = title;
        this.authorName = authorName;
        this.keyword = keyword;
        this.summary = summary;
        this.content = content;
        this.createTime = createTime;
        this.publishType = publishType;
        this.fileCode = fileCode;
        this.infoSubject = infoSubject;
        this.offerWay = offerWay;
        this.applyId = applyId;
        this.status = status;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
        this.sendTo = sendTo;
        this.lshType = lshType;
    }

   
    // Property accessors

    public String getFileId() {
        return this.fileId;
    }
    
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getInfoSource() {
        return this.infoSource;
    }
    
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Clob getContent() {
        return this.content;
    }
    
    public void setContent(Clob content) {
        this.content = content;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getPublishType() {
        return this.publishType;
    }
    
    public void setPublishType(String publishType) {
        this.publishType = publishType;
    }

    public String getFileCode() {
        return this.fileCode;
    }
    
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode;
    }

    public String getInfoSubject() {
        return this.infoSubject;
    }
    
    public void setInfoSubject(String infoSubject) {
        this.infoSubject = infoSubject;
    }

    public String getOfferWay() {
        return this.offerWay;
    }
    
    public void setOfferWay(String offerWay) {
        this.offerWay = offerWay;
    }

    public String getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }

    public String getAttr1() {
        return this.attr1;
    }
    
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    public String getAttr2() {
        return this.attr2;
    }
    
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    public String getAttr3() {
        return this.attr3;
    }
    
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }


	public Long getSendTo() {
		return sendTo;
	}


	public void setSendTo(Long sendTo) {
		this.sendTo = sendTo;
	}


	public String getLshType() {
		return lshType;
	}


	public void setLshType(String lshType) {
		this.lshType = lshType;
	}
   








}