package com.baosight.mode;

/**
 * TbGovInfoPubAudit generated by MyEclipse Persistence Tools
 */

public class TbGovInfoPubAudit implements java.io.Serializable {

	// Fields

	private String id;

	private TbGovInfoPub tbGovInfoPub;

	private Long status;
	private String statusName;
	private String rem;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbGovInfoPubAudit() {
	}

	/** full constructor */
	public TbGovInfoPubAudit(TbGovInfoPub tbGovInfoPub, Long status,
			String rem, String attr1, String attr2, String attr3) {
		this.tbGovInfoPub = tbGovInfoPub;
		this.status = status;
		this.rem = rem;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbGovInfoPub getTbGovInfoPub() {
		return this.tbGovInfoPub;
	}

	public void setTbGovInfoPub(TbGovInfoPub tbGovInfoPub) {
		this.tbGovInfoPub = tbGovInfoPub;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	

}