package com.baosight.mode;

/**
 * TbGroupAuth generated by MyEclipse Persistence Tools
 */

public class TbGroupAuth implements java.io.Serializable {

	// Fields

	private String id;

	private String groupid;

	private String authid;
	
	private String groupCode;

	// Constructors

	/** default constructor */
	public TbGroupAuth() {
	}

	/** full constructor */
	public TbGroupAuth(String id, String groupid, String authid, String groupCode) {
		this.id = id;
		this.groupid = groupid;
		this.authid = authid;
		this.groupCode = groupCode;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getAuthid() {
		return this.authid;
	}

	public void setAuthid(String authid) {
		this.authid = authid;
	}

	public String getGroupCode() {
		return groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

}