package com.baosight.mode;

/**
 * TbGroup generated by MyEclipse Persistence Tools
 */

public class TbGroup implements java.io.Serializable {

	// Fields

	private String id;

	private String code;

	private String name;

	private String deptCode;

	private String lvl;

	private String rem;

	// Constructors

	/** default constructor */
	public TbGroup() {
	}

	/** full constructor */
	public TbGroup(String code, String name, String deptCode, String lvl,
			String rem) {
		this.code = code;
		this.name = name;
		this.deptCode = deptCode;
		this.lvl = lvl;
		this.rem = rem;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getLvl() {
		return this.lvl;
	}

	public void setLvl(String lvl) {
		this.lvl = lvl;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

}