package com.baosight.mode;

/**
 * TbGroupRole generated by MyEclipse Persistence Tools
 */

public class TbGroupRole implements java.io.Serializable {

	// Fields

	private String id;

	private String groupCode;

	private String groupid;

	private String roleid;

	// Constructors

	/** default constructor */
	public TbGroupRole() {
	}

	/** full constructor */
	public TbGroupRole(String groupCode, String groupid, String roleid) {
		this.groupCode = groupCode;
		this.groupid = groupid;
		this.roleid = roleid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}