package com.baosight.mode;

/**
 * TbIndividualComm generated by MyEclipse Persistence Tools
 */

public class TbIndividualComm implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private Long inuse;

	private String remark;

	private String attr1;

	private String attr2;

	// Constructors

	/** default constructor */
	public TbIndividualComm() {
	}

	/** full constructor */
	public TbIndividualComm(String name, Long inuse, String remark,
			String attr1, String attr2) {
		this.name = name;
		this.inuse = inuse;
		this.remark = remark;
		this.attr1 = attr1;
		this.attr2 = attr2;
	}
	
	public TbIndividualComm(String name, Long inuse, String remark, String attr1) {
		this.name = name;
		this.inuse = inuse;
		this.remark = remark;
		this.attr1 = attr1;

	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getInuse() {
		return this.inuse;
	}

	public void setInuse(Long inuse) {
		this.inuse = inuse;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

}