package com.baosight.mode;

/**
 * TbLicencepolicy generated by MyEclipse Persistence Tools
 */

public class TbLicencepolicy implements java.io.Serializable {

	// Fields

	private String id;

	private String resourceid;

	private String byresourceid;

	private String tighttypeid;

	private String byresHaschild;

	// Constructors

	/** default constructor */
	public TbLicencepolicy() {
	}

	/** full constructor */
	public TbLicencepolicy(String resourceid, String byresourceid,
			String tighttypeid, String byresHaschild) {
		this.resourceid = resourceid;
		this.byresourceid = byresourceid;
		this.tighttypeid = tighttypeid;
		this.byresHaschild = byresHaschild;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(String resourceid) {
		this.resourceid = resourceid;
	}

	public String getByresourceid() {
		return this.byresourceid;
	}

	public void setByresourceid(String byresourceid) {
		this.byresourceid = byresourceid;
	}

	public String getTighttypeid() {
		return this.tighttypeid;
	}

	public void setTighttypeid(String tighttypeid) {
		this.tighttypeid = tighttypeid;
	}

	public String getByresHaschild() {
		return this.byresHaschild;
	}

	public void setByresHaschild(String byresHaschild) {
		this.byresHaschild = byresHaschild;
	}

}