package com.baosight.mode;

/**
 * TbMeetingroom generated by MyEclipse Persistence Tools
 */

public class TbMeetingroom implements java.io.Serializable {

	// Fields

	private String id;

	private String roomName;

	private String location;

	private Long capability;

	private Long status;

	private String rem;

	private String dept;

	private String attr1;

	private String attr2;

	// Constructors

	/** default constructor */
	public TbMeetingroom() {
	}

	/** full constructor */
	public TbMeetingroom(String roomName, String location, Long capability,
			Long status, String rem, String dept, String attr1, String attr2) {
		this.roomName = roomName;
		this.location = location;
		this.capability = capability;
		this.status = status;
		this.rem = rem;
		this.dept = dept;
		this.attr1 = attr1;
		this.attr2 = attr2;
	}
	
	public TbMeetingroom(String roomName, String location, Long capability,
			Long status, String rem) {
		this.roomName = roomName;
		this.location = location;
		this.capability = capability;
		this.status = status;
		this.rem = rem;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Long getCapability() {
		return this.capability;
	}

	public void setCapability(Long capability) {
		this.capability = capability;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

}