package com.baosight.mode;

import java.sql.Clob;
import java.util.Date;


/**
 * TbMessages generated by MyEclipse Persistence Tools
 */

public class TbMessages  implements java.io.Serializable {


    // Fields    

     private String id;
     private String senderId;
     private String senderName;
     private String receiversId;
     private String receiversName;
     private String receiversEmail;
     private String receiversCellphone;
     private String title;
     private Clob  content;
     private Date sendTime;
     private Long sendWay;
     private Long status;
     private String attr1;
     private String attr2;
     private String messageType;

    // Constructors

    /** default constructor */
    public TbMessages() {
    }

    
    /** full constructor */
    public TbMessages(String senderId, String senderName, String receiversId, String receiversName, String receiversEmail, String receiversCellphone, String title, Clob  content, Date sendTime, Long sendWay, Long status, String attr1, String attr2,String messageType) {
        this.senderId = senderId;
        this.senderName = senderName;
        this.receiversId = receiversId;
        this.receiversName = receiversName;
        this.receiversEmail = receiversEmail;
        this.receiversCellphone = receiversCellphone;
        this.title = title;
        this.content = content;
        this.sendTime = sendTime;
        this.sendWay = sendWay;
        this.status = status;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.messageType = messageType;
    }

    public TbMessages(String senderId, String senderName, String receiversId, String receiversName, String receiversCellphone, String title, Clob content,Date sendTime, Long sendWay, Long status) {
        this.senderId = senderId;
        this.senderName = senderName;
        this.receiversId = receiversId;
        this.receiversName = receiversName;
        this.receiversCellphone = receiversCellphone;
        this.title = title;
        this.content = content;
        this.sendTime=sendTime;
        this.sendWay = sendWay;
        this.status = status;
    }
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getSenderId() {
        return this.senderId;
    }
    
    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getSenderName() {
        return this.senderName;
    }
    
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public String getReceiversId() {
        return this.receiversId;
    }
    
    public void setReceiversId(String receiversId) {
        this.receiversId = receiversId;
    }

    public String getReceiversName() {
        return this.receiversName;
    }
    
    public void setReceiversName(String receiversName) {
        this.receiversName = receiversName;
    }

    public String getReceiversEmail() {
        return this.receiversEmail;
    }
    
    public void setReceiversEmail(String receiversEmail) {
        this.receiversEmail = receiversEmail;
    }

    public String getReceiversCellphone() {
        return this.receiversCellphone;
    }
    
    public void setReceiversCellphone(String receiversCellphone) {
        this.receiversCellphone = receiversCellphone;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public Clob  getContent() {
        return this.content;
    }
    
    public void setContent(Clob  content) {
        this.content = content;
    }

    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    public Long getSendWay() {
        return this.sendWay;
    }
    
    public void setSendWay(Long sendWay) {
        this.sendWay = sendWay;
    }

    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }

    public String getAttr1() {
        return this.attr1;
    }
    
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    public String getAttr2() {
        return this.attr2;
    }
    
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }


	public String getMessageType() {
		return messageType;
	}


	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}
   








}