package com.baosight.mode;

import java.util.Date;

/**
 * TbNotiesId generated by MyEclipse Persistence Tools
 */

public class TbNotiesId implements java.io.Serializable {

	// Fields

	private String id;

	private Long noticesType;

	private String noticesUrl;

	private String noticesTo;

	private Date noticesTime;

	private Long noticesLevel;

	private String rem;

	// Constructors

	/** default constructor */
	public TbNotiesId() {
	}

	/** full constructor */
	public TbNotiesId(String id, Long noticesType, String noticesUrl,
			String noticesTo, Date noticesTime, Long noticesLevel, String rem) {
		this.id = id;
		this.noticesType = noticesType;
		this.noticesUrl = noticesUrl;
		this.noticesTo = noticesTo;
		this.noticesTime = noticesTime;
		this.noticesLevel = noticesLevel;
		this.rem = rem;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getNoticesType() {
		return this.noticesType;
	}

	public void setNoticesType(Long noticesType) {
		this.noticesType = noticesType;
	}

	public String getNoticesUrl() {
		return this.noticesUrl;
	}

	public void setNoticesUrl(String noticesUrl) {
		this.noticesUrl = noticesUrl;
	}

	public String getNoticesTo() {
		return this.noticesTo;
	}

	public void setNoticesTo(String noticesTo) {
		this.noticesTo = noticesTo;
	}

	public Date getNoticesTime() {
		return this.noticesTime;
	}

	public void setNoticesTime(Date noticesTime) {
		this.noticesTime = noticesTime;
	}

	public Long getNoticesLevel() {
		return this.noticesLevel;
	}

	public void setNoticesLevel(Long noticesLevel) {
		this.noticesLevel = noticesLevel;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbNotiesId))
			return false;
		TbNotiesId castOther = (TbNotiesId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getNoticesType() == castOther.getNoticesType()) || (this
						.getNoticesType() != null
						&& castOther.getNoticesType() != null && this
						.getNoticesType().equals(castOther.getNoticesType())))
				&& ((this.getNoticesUrl() == castOther.getNoticesUrl()) || (this
						.getNoticesUrl() != null
						&& castOther.getNoticesUrl() != null && this
						.getNoticesUrl().equals(castOther.getNoticesUrl())))
				&& ((this.getNoticesTo() == castOther.getNoticesTo()) || (this
						.getNoticesTo() != null
						&& castOther.getNoticesTo() != null && this
						.getNoticesTo().equals(castOther.getNoticesTo())))
				&& ((this.getNoticesTime() == castOther.getNoticesTime()) || (this
						.getNoticesTime() != null
						&& castOther.getNoticesTime() != null && this
						.getNoticesTime().equals(castOther.getNoticesTime())))
				&& ((this.getNoticesLevel() == castOther.getNoticesLevel()) || (this
						.getNoticesLevel() != null
						&& castOther.getNoticesLevel() != null && this
						.getNoticesLevel().equals(castOther.getNoticesLevel())))
				&& ((this.getRem() == castOther.getRem()) || (this.getRem() != null
						&& castOther.getRem() != null && this.getRem().equals(
						castOther.getRem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getNoticesType() == null ? 0 : this.getNoticesType()
						.hashCode());
		result = 37
				* result
				+ (getNoticesUrl() == null ? 0 : this.getNoticesUrl()
						.hashCode());
		result = 37 * result
				+ (getNoticesTo() == null ? 0 : this.getNoticesTo().hashCode());
		result = 37
				* result
				+ (getNoticesTime() == null ? 0 : this.getNoticesTime()
						.hashCode());
		result = 37
				* result
				+ (getNoticesLevel() == null ? 0 : this.getNoticesLevel()
						.hashCode());
		result = 37 * result
				+ (getRem() == null ? 0 : this.getRem().hashCode());
		return result;
	}

}