package com.baosight.mode;

/**
 * TbNoties generated by MyEclipse Persistence Tools
 */

public class TbNoties implements java.io.Serializable {

	// Fields

	private TbNotiesId id;

	// Constructors

	/** default constructor */
	public TbNoties() {
	}

	/** full constructor */
	public TbNoties(TbNotiesId id) {
		this.id = id;
	}

	// Property accessors

	public TbNotiesId getId() {
		return this.id;
	}

	public void setId(TbNotiesId id) {
		this.id = id;
	}

}