package com.baosight.mode;

import java.util.Date;

/**
 * TbOaHoliday generated by MyEclipse Persistence Tools
 */

public class TbOaHoliday implements java.io.Serializable {

	// Fields

	private String id;

	private Date holiday;

	private String amPm;

	private Float day;

	private String deptId;

	private String description;

	private String arb;

	// Constructors

	/** default constructor */
	public TbOaHoliday() {
	}

	public TbOaHoliday(Date holiday, String amPm,Float day,String description) {
		this.holiday = holiday;
		this.amPm = amPm;
		this.day=day;
		this.description = description;
	}
	
	
	/** full constructor */
	public TbOaHoliday(Date holiday, String amPm, Float day, String deptId,
			String description, String arb) {
		this.holiday = holiday;
		this.amPm = amPm;
		this.day = day;
		this.deptId = deptId;
		this.description = description;
		this.arb = arb;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getHoliday() {
		return this.holiday;
	}

	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}

	public String getAmPm() {
		return this.amPm;
	}

	public void setAmPm(String amPm) {
		this.amPm = amPm;
	}

	public Float getDay() {
		return this.day;
	}

	public void setDay(Float day) {
		this.day = day;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getArb() {
		return this.arb;
	}

	public void setArb(String arb) {
		this.arb = arb;
	}

}