package com.baosight.mode;

import java.util.Date;

/**
 * TbObligeeMsg generated by MyEclipse Persistence Tools
 */

public class TbObligeeMsg implements java.io.Serializable {

	// Fields

	private String id;

	private String obligeeName;

	private String contentMsg;

	private String involveMsg;

	private Date signDate;

	private String year;

	private String autoNo;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbObligeeMsg() {
	}

	/** full constructor */
	public TbObligeeMsg(String obligeeName, String contentMsg,
			String involveMsg, Date signDate, String year, String autoNo,
			String attr1, String attr2, String attr3) {
		this.obligeeName = obligeeName;
		this.contentMsg = contentMsg;
		this.involveMsg = involveMsg;
		this.signDate = signDate;
		this.year = year;
		this.autoNo = autoNo;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObligeeName() {
		return this.obligeeName;
	}

	public void setObligeeName(String obligeeName) {
		this.obligeeName = obligeeName;
	}

	public String getContentMsg() {
		return this.contentMsg;
	}

	public void setContentMsg(String contentMsg) {
		this.contentMsg = contentMsg;
	}

	public String getInvolveMsg() {
		return this.involveMsg;
	}

	public void setInvolveMsg(String involveMsg) {
		this.involveMsg = involveMsg;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getAutoNo() {
		return this.autoNo;
	}

	public void setAutoNo(String autoNo) {
		this.autoNo = autoNo;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}