package com.baosight.mode;

import java.util.Date;

/**
 * TbObligeeOpinion generated by MyEclipse Persistence Tools
 */

public class TbObligeeOpinion implements java.io.Serializable {

	// Fields

	private String id;

	private String consultName;

	private String contentMsg;

	private String involveMsg;

	private String year;

	private String autoNo;

	private String opinion;

	private Date replyDate;

	private String address;

	private String postalcode;

	private String attr1;

	private String attr2;

	private String attr3;

	private Date signDate;

	// Constructors

	/** default constructor */
	public TbObligeeOpinion() {
	}

	/** full constructor */
	public TbObligeeOpinion(String consultName, String contentMsg,
			String involveMsg, String year, String autoNo, String opinion,
			Date replyDate, String address, String postalcode, String attr1,
			String attr2, String attr3, Date signDate) {
		this.consultName = consultName;
		this.contentMsg = contentMsg;
		this.involveMsg = involveMsg;
		this.year = year;
		this.autoNo = autoNo;
		this.opinion = opinion;
		this.replyDate = replyDate;
		this.address = address;
		this.postalcode = postalcode;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.signDate = signDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getConsultName() {
		return this.consultName;
	}

	public void setConsultName(String consultName) {
		this.consultName = consultName;
	}

	public String getContentMsg() {
		return this.contentMsg;
	}

	public void setContentMsg(String contentMsg) {
		this.contentMsg = contentMsg;
	}

	public String getInvolveMsg() {
		return this.involveMsg;
	}

	public void setInvolveMsg(String involveMsg) {
		this.involveMsg = involveMsg;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getAutoNo() {
		return this.autoNo;
	}

	public void setAutoNo(String autoNo) {
		this.autoNo = autoNo;
	}

	public String getOpinion() {
		return this.opinion;
	}

	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

	public Date getReplyDate() {
		return this.replyDate;
	}

	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

}