package com.baosight.mode;

import java.util.Date;

/**
 * TbOpinionConsult generated by MyEclipse Persistence Tools
 */

public class TbOpinionConsult implements java.io.Serializable {

	// Fields

	private String id;

	private String govInfoId;

	private String attr1;

	private String attr2;

	private String numb;

	private String consultedName;

	private Date arriveDate;

	private String applicant;

	private String cause;

	private String address;

	private String postalcode;

	private String attr3;

	private String attr4;

	private Date signDate;

	// Constructors

	/** default constructor */
	public TbOpinionConsult() {
	}

	/** minimal constructor */
	public TbOpinionConsult(String govInfoId) {
		this.govInfoId = govInfoId;
	}
	public TbOpinionConsult(String govInfoId, String attr1, String attr2,
			String numb, String consultedName, Date arriveDate,
			String applicant, String cause, String address, String postalcode,
			 Date signDate) {
		this.govInfoId = govInfoId;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.numb = numb;
		this.consultedName = consultedName;
		this.arriveDate = arriveDate;
		this.applicant = applicant;
		this.cause = cause;
		this.address = address;
		this.postalcode = postalcode;
		this.signDate = signDate;
	}
	public TbOpinionConsult(String id,String govInfoId, String attr1, String attr2,
			String numb, String consultedName, Date arriveDate,
			String applicant, String cause, String address, String postalcode,
			 Date signDate) {
		this.id = id;
		this.govInfoId = govInfoId;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.numb = numb;
		this.consultedName = consultedName;
		this.arriveDate = arriveDate;
		this.applicant = applicant;
		this.cause = cause;
		this.address = address;
		this.postalcode = postalcode;
		this.signDate = signDate;
	}
	/** full constructor */
	public TbOpinionConsult(String govInfoId, String attr1, String attr2,
			String numb, String consultedName, Date arriveDate,
			String applicant, String cause, String address, String postalcode,
			String attr3, String attr4, Date signDate) {
		this.govInfoId = govInfoId;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.numb = numb;
		this.consultedName = consultedName;
		this.arriveDate = arriveDate;
		this.applicant = applicant;
		this.cause = cause;
		this.address = address;
		this.postalcode = postalcode;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.signDate = signDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGovInfoId() {
		return this.govInfoId;
	}

	public void setGovInfoId(String govInfoId) {
		this.govInfoId = govInfoId;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getNumb() {
		return this.numb;
	}

	public void setNumb(String numb) {
		this.numb = numb;
	}

	public String getConsultedName() {
		return this.consultedName;
	}

	public void setConsultedName(String consultedName) {
		this.consultedName = consultedName;
	}

	public Date getArriveDate() {
		return this.arriveDate;
	}

	public void setArriveDate(Date arriveDate) {
		this.arriveDate = arriveDate;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

}