package com.baosight.mode;

/**
 * TbPst generated by MyEclipse Persistence Tools
 */

public class TbPst implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String lvl;

	private String code;
	
	private String deptid;
	
	private Long defOrder;

	// Constructors

	/** default constructor */
	public TbPst() {
	}

	/** full constructor */
	public TbPst(String name, String lvl, String code) {
		this.name = name;
		this.lvl = lvl;
		this.code = code;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvl() {
		return this.lvl;
	}

	public void setLvl(String lvl) {
		this.lvl = lvl;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getDefOrder() {
		return defOrder;
	}

	public void setDefOrder(Long defOrder) {
		this.defOrder = defOrder;
	}

	public String getDeptid() {
		return deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

}