package com.baosight.mode;

import java.util.Date;

/**
 * TbReply5 generated by MyEclipse Persistence Tools
 */

public class TbReply5 implements java.io.Serializable {

	// Fields

	private String id;

	private String applicant;

	private String year;

	private String applyNo;

	private Date applyDate;

	private String applyTitle;

	private String department;

	private String contactAddr;

	private Date signDate;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbReply5() {
	}

	/** full constructor */
	public TbReply5(String applicant, String year, String applyNo,
			Date applyDate, String applyTitle, String department,
			String contactAddr, Date signDate, String attr1, String attr2,
			String attr3) {
		this.applicant = applicant;
		this.year = year;
		this.applyNo = applyNo;
		this.applyDate = applyDate;
		this.applyTitle = applyTitle;
		this.department = department;
		this.contactAddr = contactAddr;
		this.signDate = signDate;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getApplyTitle() {
		return this.applyTitle;
	}

	public void setApplyTitle(String applyTitle) {
		this.applyTitle = applyTitle;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getContactAddr() {
		return this.contactAddr;
	}

	public void setContactAddr(String contactAddr) {
		this.contactAddr = contactAddr;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}