package com.baosight.mode;

/**
 * TbRighttype generated by MyEclipse Persistence Tools
 */

public class TbRighttype implements java.io.Serializable {

	// Fields

	private String id;

	private Long code;

	private String name;

	private String appsysid;

	private String funid;
	
	private Long insure;


	// Constructors

	public Long getInsure() {
		return insure;
	}

	public void setInsure(Long insure) {
		this.insure = insure;
	}

	/** default constructor */
	public TbRighttype() {
	}

	/** full constructor */
	public TbRighttype(String id, Long code, String name, String appsysid, String funid) {
		
	}

	public TbRighttype(String id, Long code, String name, String appsysid,
			String funid, Long insure) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.appsysid = appsysid;
		this.funid = funid;
		this.insure = insure;
	}
	
	public TbRighttype(Long code, String name, String appsysid, String funid,Long insure) {
		this.code = code;
		this.name = name;
		this.appsysid = appsysid;
		this.funid = funid;
		this.insure=insure;
	}

	/** full constructor */

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getCode() {
		return this.code;
	}

	public void setCode(Long code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAppsysid() {
		return appsysid;
	}

	public void setAppsysid(String appsysid) {
		this.appsysid = appsysid;
	}

	public String getFunid() {
		return funid;
	}

	public void setFunid(String funid) {
		this.funid = funid;
	}


}