package com.baosight.mode;

/**
 * TbRoleCla generated by MyEclipse Persistence Tools
 */

public class TbRoleCla implements java.io.Serializable {

	// Fields

	private String id;

	private String claId;

	private String roleId;

	private String attr1;

	// Constructors

	/** default constructor */
	public TbRoleCla() {
	}

	/** full constructor */
	public TbRoleCla(String claId, String roleId, String attr1) {
		this.claId = claId;
		this.roleId = roleId;
		this.attr1 = attr1;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getClaId() {
		return this.claId;
	}

	public void setClaId(String claId) {
		this.claId = claId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

}