package com.baosight.mode;

/**
 * TbShareFile generated by MyEclipse Persistence Tools
 */

public class TbShareFile implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private String explanation;

	private String type;

	private String originallyName;

	private String serverName;

	private String isShare;

	// Constructors

	/** default constructor */
	public TbShareFile() {
	}

	/** full constructor */
	public TbShareFile(String userid, String explanation, String type,
			String originallyName, String serverName, String isShare) {
		this.userid = userid;
		this.explanation = explanation;
		this.type = type;
		this.originallyName = originallyName;
		this.serverName = serverName;
		this.isShare = isShare;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOriginallyName() {
		return this.originallyName;
	}

	public void setOriginallyName(String originallyName) {
		this.originallyName = originallyName;
	}

	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	public String getIsShare() {
		return this.isShare;
	}

	public void setIsShare(String isShare) {
		this.isShare = isShare;
	}

}