package com.baosight.mode;

/**
 * TbSmsDepart generated by MyEclipse Persistence Tools
 */

public class TbSmsDepart implements java.io.Serializable {

	// Fields

	private String id;

	private String departname;

	private String superiorId;

	private Long deptSort;

	private Long smscount;

	// Constructors

	/** default constructor */
	public TbSmsDepart() {
	}

	/** minimal constructor */
	public TbSmsDepart(String departname) {
		this.departname = departname;
	}

	/** full constructor */
	public TbSmsDepart(String departname, String superiorId, Long deptSort,
			Long smscount) {
		this.departname = departname;
		this.superiorId = superiorId;
		this.deptSort = deptSort;
		this.smscount = smscount;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDepartname() {
		return this.departname;
	}

	public void setDepartname(String departname) {
		this.departname = departname;
	}

	public String getSuperiorId() {
		return this.superiorId;
	}

	public void setSuperiorId(String superiorId) {
		this.superiorId = superiorId;
	}

	public Long getDeptSort() {
		return this.deptSort;
	}

	public void setDeptSort(Long deptSort) {
		this.deptSort = deptSort;
	}

	public Long getSmscount() {
		return this.smscount;
	}

	public void setSmscount(Long smscount) {
		this.smscount = smscount;
	}

}