package com.baosight.mode;

/**
 * TbSmsSubscribe generated by MyEclipse Persistence Tools
 */

public class TbSmsSubscribe implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private String subjectid;

	private Long mobileNum;

	private String username;

	private String subjectname;

	private String infofeeType;

	private String substime;

	private String subjecttype1;

	private String subjecttype2;

	private String departid;

	// Constructors

	/** default constructor */
	public TbSmsSubscribe() {
	}

	/** minimal constructor */
	public TbSmsSubscribe(String userid, String subjectid) {
		this.userid = userid;
		this.subjectid = subjectid;
	}

	/** full constructor */
	public TbSmsSubscribe(String userid, String subjectid, Long mobileNum,
			String username, String subjectname, String infofeeType,
			String substime, String subjecttype1, String subjecttype2,
			String departid) {
		this.userid = userid;
		this.subjectid = subjectid;
		this.mobileNum = mobileNum;
		this.username = username;
		this.subjectname = subjectname;
		this.infofeeType = infofeeType;
		this.substime = substime;
		this.subjecttype1 = subjecttype1;
		this.subjecttype2 = subjecttype2;
		this.departid = departid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(String subjectid) {
		this.subjectid = subjectid;
	}

	public Long getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(Long mobileNum) {
		this.mobileNum = mobileNum;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSubjectname() {
		return this.subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	public String getInfofeeType() {
		return this.infofeeType;
	}

	public void setInfofeeType(String infofeeType) {
		this.infofeeType = infofeeType;
	}

	public String getSubstime() {
		return this.substime;
	}

	public void setSubstime(String substime) {
		this.substime = substime;
	}

	public String getSubjecttype1() {
		return this.subjecttype1;
	}

	public void setSubjecttype1(String subjecttype1) {
		this.subjecttype1 = subjecttype1;
	}

	public String getSubjecttype2() {
		return this.subjecttype2;
	}

	public void setSubjecttype2(String subjecttype2) {
		this.subjecttype2 = subjecttype2;
	}

	public String getDepartid() {
		return this.departid;
	}

	public void setDepartid(String departid) {
		this.departid = departid;
	}

}