package com.baosight.mode;

/**
 * TbUserAuth generated by MyEclipse Persistence Tools
 */

public class TbUserAuth implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private String authid;

	// Constructors

	/** default constructor */
	public TbUserAuth() {
	}

	/** full constructor */
	public TbUserAuth(String userid, String authid) {
		this.userid = userid;
		this.authid = authid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getAuthid() {
		return this.authid;
	}

	public void setAuthid(String authid) {
		this.authid = authid;
	}

}