package com.baosight.mode;

/**
 * TbUserGroup generated by MyEclipse Persistence Tools
 */

public class TbUserGroup implements java.io.Serializable {

	// Fields

	private String id;

	private String groupCode;

	private String userId;

	private String groupid;

	// Constructors

	/** default constructor */
	public TbUserGroup() {
	}

	/** full constructor */
	public TbUserGroup(String groupCode, String userId, String groupid) {
		this.groupCode = groupCode;
		this.userId = userId;
		this.groupid = groupid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

}