package com.baosight.mode;

/**
 * TbUserAppsys generated by MyEclipse Persistence Tools
 */

public class TbUserAppsys implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private String appid;

	private String funid;

	// Constructors

	/** default constructor */
	public TbUserAppsys() {
	}

	/** full constructor */
	public TbUserAppsys(String userid, String appid, String funid) {
		this.userid = userid;
		this.appid = appid;
		this.funid = funid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	public String getFunid() {
		return this.funid;
	}

	public void setFunid(String funid) {
		this.funid = funid;
	}

}