package com.baosight.mode;

/**
 * TbUserinfo generated by MyEclipse Persistence Tools
 */

public class TbUserinfo implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private String birthday;

	private String email;

	private String linkaddress;

	private String handset;

	private String phone;

	// Constructors

	/** default constructor */
	public TbUserinfo() {
	}

	/** minimal constructor */
	public TbUserinfo(String userid) {
		this.userid = userid;
	}

	/** full constructor */
	public TbUserinfo(String userid, String birthday, String email,
			String linkaddress, String handset, String phone) {
		this.userid = userid;
		this.birthday = birthday;
		this.email = email;
		this.linkaddress = linkaddress;
		this.handset = handset;
		this.phone = phone;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLinkaddress() {
		return this.linkaddress;
	}

	public void setLinkaddress(String linkaddress) {
		this.linkaddress = linkaddress;
	}

	public String getHandset() {
		return this.handset;
	}

	public void setHandset(String handset) {
		this.handset = handset;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}