package com.baosight.mode;



/**
 * TbVehicles generated by MyEclipse - Hibernate Tools
 */

public class TbVehicles  implements java.io.Serializable {


    // Fields    

     private String id;
     private String license;
     private String model;
     private Long capacity;
     private Long status;
     private String rem;
     private String belSys;
     private String attr1;
     private String attr2;


    // Constructors

    /** default constructor */
    public TbVehicles() {
    }

    public TbVehicles(String license, String model, Long capacity, Long status, String rem) {
        this.license = license;
        this.model = model;
        this.capacity = capacity;
        this.status = status;
        this.rem = rem;
    }
    /** full constructor */
    public TbVehicles(String license, String model, Long capacity, Long status, String rem, String belSys, String attr1, String attr2) {
        this.license = license;
        this.model = model;
        this.capacity = capacity;
        this.status = status;
        this.rem = rem;
        this.belSys = belSys;
        this.attr1 = attr1;
        this.attr2 = attr2;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getLicense() {
        return this.license;
    }
    
    public void setLicense(String license) {
        this.license = license;
    }

    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    public Long getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }

    public String getRem() {
        return this.rem;
    }
    
    public void setRem(String rem) {
        this.rem = rem;
    }

    public String getBelSys() {
        return this.belSys;
    }
    
    public void setBelSys(String belSys) {
        this.belSys = belSys;
    }

    public String getAttr1() {
        return this.attr1;
    }
    
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    public String getAttr2() {
        return this.attr2;
    }
    
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }
   








}