package com.baosight.mode;

import java.util.Date;

/**
 * TbWarningPub generated by MyEclipse Persistence Tools
 */

public class TbWarningPub implements java.io.Serializable {

	// Fields

	private String id;

	private String signal;

	private String resp;

	private Date pubstart;

	private Date pubend;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbWarningPub() {
	}

	/** full constructor */
	public TbWarningPub(String signal, String resp, Date pubstart, Date pubend,
			String attr1, String attr2, String attr3) {
		this.signal = signal;
		this.resp = resp;
		this.pubstart = pubstart;
		this.pubend = pubend;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSignal() {
		return this.signal;
	}

	public void setSignal(String signal) {
		this.signal = signal;
	}

	public String getResp() {
		return this.resp;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}

	public Date getPubstart() {
		return this.pubstart;
	}

	public void setPubstart(Date pubstart) {
		this.pubstart = pubstart;
	}

	public Date getPubend() {
		return this.pubend;
	}

	public void setPubend(Date pubend) {
		this.pubend = pubend;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}