package com.baosight.mode;

import java.util.Date;

/**
 * TbWrit9 generated by MyEclipse Persistence Tools
 */

public class TbWrit9 implements java.io.Serializable {

	// Fields

	private String id;

	private String busId;

	private String wsh;

	private String sqmc;

	private String sjzm;

	private Date createdate;

	private Date applydate;

	// Constructors

	/** default constructor */
	public TbWrit9() {
	}

	/** full constructor */
	public TbWrit9(String busId, String wsh, String sqmc, String sjzm,
			Date createdate, Date applydate) {
		this.busId = busId;
		this.wsh = wsh;
		this.sqmc = sqmc;
		this.sjzm = sjzm;
		this.createdate = createdate;
		this.applydate = applydate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	public String getWsh() {
		return this.wsh;
	}

	public void setWsh(String wsh) {
		this.wsh = wsh;
	}

	public String getSqmc() {
		return this.sqmc;
	}

	public void setSqmc(String sqmc) {
		this.sqmc = sqmc;
	}

	public String getSjzm() {
		return this.sjzm;
	}

	public void setSjzm(String sjzm) {
		this.sjzm = sjzm;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

}