package com.baosight.mode;

import java.util.Date;

/**
 * TbWrit8 generated by MyEclipse Persistence Tools
 */

public class TbWrit8 implements java.io.Serializable {

	// Fields

	private String id;

	private String busId;

	private Date applydate;

	private String sqmc;

	private String sjzm;

	private String zx;

	private String lxfs;
	private String wsh;
	private Date createdate;

	// Constructors

	/** default constructor */
	public TbWrit8() {
	}

	/** full constructor */
	public TbWrit8(String busId, Date applydate, String sqmc, String sjzm,
			String zx, String lxfs, Date createdate) {
		this.busId = busId;
		this.applydate = applydate;
		this.sqmc = sqmc;
		this.sjzm = sjzm;
		this.zx = zx;
		this.lxfs = lxfs;
		this.createdate = createdate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getSqmc() {
		return this.sqmc;
	}

	public void setSqmc(String sqmc) {
		this.sqmc = sqmc;
	}

	public String getSjzm() {
		return this.sjzm;
	}

	public void setSjzm(String sjzm) {
		this.sjzm = sjzm;
	}

	public String getZx() {
		return this.zx;
	}

	public void setZx(String zx) {
		this.zx = zx;
	}

	public String getLxfs() {
		return this.lxfs;
	}

	public void setLxfs(String lxfs) {
		this.lxfs = lxfs;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}
	public String getWsh() {
		return this.wsh;
	}

	public void setWsh(String wsh) {
		this.wsh = wsh;
	}
}