package com.baosight.mode;

/**
 * TbZfxxgkgzs generated by MyEclipse Persistence Tools
 */

public class TbZfxxgkgzs implements java.io.Serializable {

	// Fields
	private String id;
	
	private String infoId;

	private String attr1;

	private String attr2;

	private String attr3;

	private String attr4;

	private String attr5;

	private String attr6;

	private String attr7;

	private String attr8;

	private String attr9;

	private String attr10;

	private String attr11;

	private String attr12;

	private String attr13;

	private String attr14;

	private String attr15;

	private String attr16;

	private String attr17;

	private String attr18;

	private String attr19;

	private String attr20;

	// Constructors

	/** default constructor */
	public TbZfxxgkgzs() {
	}

	/** minimal constructor */
	public TbZfxxgkgzs(String attr1, String attr2, String attr3, String attr4,
			String attr5, String attr6, String attr7, String attr8,
			String attr9, String attr10, String attr11, String attr12,
			String attr13, String attr14, String attr15, String attr16,
			String attr17, String attr18, String attr19, String attr20) {
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.attr5 = attr5;
		this.attr6 = attr6;
		this.attr7 = attr7;
		this.attr8 = attr8;
		this.attr9 = attr9;
		this.attr10 = attr10;
		this.attr11 = attr11;
		this.attr12 = attr12;
		this.attr13 = attr13;
		this.attr14 = attr14;
		this.attr15 = attr15;
		this.attr16 = attr16;
		this.attr17 = attr17;
		this.attr18 = attr18;
		this.attr19 = attr19;
		this.attr20 = attr20;
	}

	/** full constructor */
	public TbZfxxgkgzs(String infoId, String attr1, String attr2, String attr3,
			String attr4, String attr5, String attr6, String attr7,
			String attr8, String attr9, String attr10, String attr11,
			String attr12, String attr13, String attr14, String attr15,
			String attr16, String attr17, String attr18, String attr19,
			String attr20) {
		this.infoId = infoId;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.attr5 = attr5;
		this.attr6 = attr6;
		this.attr7 = attr7;
		this.attr8 = attr8;
		this.attr9 = attr9;
		this.attr10 = attr10;
		this.attr11 = attr11;
		this.attr12 = attr12;
		this.attr13 = attr13;
		this.attr14 = attr14;
		this.attr15 = attr15;
		this.attr16 = attr16;
		this.attr17 = attr17;
		this.attr18 = attr18;
		this.attr19 = attr19;
		this.attr20 = attr20;
	}

	// Property accessors

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	public String getAttr5() {
		return this.attr5;
	}

	public void setAttr5(String attr5) {
		this.attr5 = attr5;
	}

	public String getAttr6() {
		return this.attr6;
	}

	public void setAttr6(String attr6) {
		this.attr6 = attr6;
	}

	public String getAttr7() {
		return this.attr7;
	}

	public void setAttr7(String attr7) {
		this.attr7 = attr7;
	}

	public String getAttr8() {
		return this.attr8;
	}

	public void setAttr8(String attr8) {
		this.attr8 = attr8;
	}

	public String getAttr9() {
		return this.attr9;
	}

	public void setAttr9(String attr9) {
		this.attr9 = attr9;
	}

	public String getAttr10() {
		return this.attr10;
	}

	public void setAttr10(String attr10) {
		this.attr10 = attr10;
	}

	public String getAttr11() {
		return this.attr11;
	}

	public void setAttr11(String attr11) {
		this.attr11 = attr11;
	}

	public String getAttr12() {
		return this.attr12;
	}

	public void setAttr12(String attr12) {
		this.attr12 = attr12;
	}

	public String getAttr13() {
		return this.attr13;
	}

	public void setAttr13(String attr13) {
		this.attr13 = attr13;
	}

	public String getAttr14() {
		return this.attr14;
	}

	public void setAttr14(String attr14) {
		this.attr14 = attr14;
	}

	public String getAttr15() {
		return this.attr15;
	}

	public void setAttr15(String attr15) {
		this.attr15 = attr15;
	}

	public String getAttr16() {
		return this.attr16;
	}

	public void setAttr16(String attr16) {
		this.attr16 = attr16;
	}

	public String getAttr17() {
		return this.attr17;
	}

	public void setAttr17(String attr17) {
		this.attr17 = attr17;
	}

	public String getAttr18() {
		return this.attr18;
	}

	public void setAttr18(String attr18) {
		this.attr18 = attr18;
	}

	public String getAttr19() {
		return this.attr19;
	}

	public void setAttr19(String attr19) {
		this.attr19 = attr19;
	}

	public String getAttr20() {
		return this.attr20;
	}

	public void setAttr20(String attr20) {
		this.attr20 = attr20;
	}

}