package com.baosight.mode;

import java.util.Date;

/**
 * TbZfxxgksqdf generated by MyEclipse Persistence Tools
 */

public class TbZfxxgksqdf implements java.io.Serializable {

	// Fields

	private String id;

	private String infoId;

	private String lsNo;

	private String applicant;

	private Date sqTime;

	private Date dfTime;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbZfxxgksqdf() {
	}

	/** minimal constructor */
	public TbZfxxgksqdf(String infoId) {
		this.infoId = infoId;
	}

	/** full constructor */
	public TbZfxxgksqdf(String infoId, String lsNo, String applicant,
			Date sqTime, Date dfTime, String attr1, String attr2, String attr3) {
		this.infoId = infoId;
		this.lsNo = lsNo;
		this.applicant = applicant;
		this.sqTime = sqTime;
		this.dfTime = dfTime;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getLsNo() {
		return this.lsNo;
	}

	public void setLsNo(String lsNo) {
		this.lsNo = lsNo;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Date getSqTime() {
		return this.sqTime;
	}

	public void setSqTime(Date sqTime) {
		this.sqTime = sqTime;
	}

	public Date getDfTime() {
		return this.dfTime;
	}

	public void setDfTime(Date dfTime) {
		this.dfTime = dfTime;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}