package com.baosight.mode;

import java.util.Date;

/**
 * TbZfxxgkdfTwo generated by MyEclipse Persistence Tools
 */

public class TbZfxxgkdfTwo implements java.io.Serializable {

	// Fields

	private String id;

	private String lsNo;

	private String appliName;

	private Date receiveDate;

	private String infoName;

	private String infoRank;

	private Date sendDate;

	private String attr1;

	// Constructors

	/** default constructor */
	public TbZfxxgkdfTwo() {
	}

	/** full constructor */
	public TbZfxxgkdfTwo(String lsNo, String appliName, Date receiveDate,
			String infoName, String infoRank, Date sendDate, String attr1) {
		this.lsNo = lsNo;
		this.appliName = appliName;
		this.receiveDate = receiveDate;
		this.infoName = infoName;
		this.infoRank = infoRank;
		this.sendDate = sendDate;
		this.attr1 = attr1;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLsNo() {
		return this.lsNo;
	}

	public void setLsNo(String lsNo) {
		this.lsNo = lsNo;
	}

	public String getAppliName() {
		return this.appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getInfoName() {
		return this.infoName;
	}

	public void setInfoName(String infoName) {
		this.infoName = infoName;
	}

	public String getInfoRank() {
		return this.infoRank;
	}

	public void setInfoRank(String infoRank) {
		this.infoRank = infoRank;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

}