package com.baosight.mode;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TFileAllZf generated by MyEclipse Persistence Tools
 */
public class TFileAllZf extends AbstractTFileAllZf implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TFileAllZf() {
	}

	/** minimal constructor */
	public TFileAllZf(String title, Date createtime, Long typeid, Long folderid) {
		super(title, createtime, typeid, folderid);
	}

	/** full constructor */
	public TFileAllZf(String title, Date createtime, Date starttime,
			Date endtime, String author, Long typeid, Long folderid,
			String purview, String isvalid, Long keyword1, Long keyword2,
			Long keyword3, Long keyword4, Long temp, Long hit, Long inputuer,
			Long deptid, Long infotype, String filenumber, Long issueddept1,
			String issueddept2, Long carriertype, String getid,
			String keyword5, Long lsh, Long auditing, String reason) {
		super(title, createtime, starttime, endtime, author, typeid, folderid,
				purview, isvalid, keyword1, keyword2, keyword3, keyword4, temp,
				hit, inputuer, deptid, infotype, filenumber, issueddept1,
				issueddept2, carriertype, getid, keyword5, lsh, auditing,
				reason);
	}

}
