package com.baosight.mode;

// Generated by MyEclipse Persistence Tools

/**
 * VwXzxk generated by MyEclipse Persistence Tools
 */
public class VwXzxk extends AbstractVwXzxk implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public VwXzxk() {
	}

	/** full constructor */
	public VwXzxk(VwXzxkId id) {
		super(id);
	}

}
