package com.baosight.dao;



/**
 * TUserId generated by MyEclipse Persistence Tools
 */

public class TUserId extends BasePOJO implements java.io.Serializable {


    // Fields    

     private String name;
     private String orgid;
     private String deleted;
     private String rightid;
     private String ename;
     private String parentid;
     private String FUsing;
     private String outuser;
     private String cname;
     private String repassword;
     private String remark;
     private String templatename;
     private String resourcetype;
     private String childrenid;
     private String address;
     private String password;
     private String password2;
     private String position;
     private String forumlogin;
     private String postnumber;
     private String loginnumber;
     private String ekeyuser;
     private String mainpage;
     private String styleid;
     private String FIsout;
     private String FIcon;
     private String FDescription;
     private String FName;
     private String FNumber;
     private String FContent;
     private String num;
     private String loginip;
     private String logintime;
     private String roles;


    // Constructors

    /** default constructor */
    public TUserId() {
    }

    
    /** full constructor */
    public TUserId(String name, String orgid, String id, String deleted, String rightid, String ename, String parentid, String FUsing, String outuser, String cname, String repassword, String remark, String templatename, String resourcetype, String childrenid, String address, String password, String password2, String position, String forumlogin, String postnumber, String loginnumber, String ekeyuser, String mainpage, String styleid, String FIsout, String FIcon, String FDescription, String FName, String FNumber, String FContent, String num, String loginip, String logintime, String roles) {
        this.name = name;
        this.orgid = orgid;
        this.id = id;
        this.deleted = deleted;
        this.rightid = rightid;
        this.ename = ename;
        this.parentid = parentid;
        this.FUsing = FUsing;
        this.outuser = outuser;
        this.cname = cname;
        this.repassword = repassword;
        this.remark = remark;
        this.templatename = templatename;
        this.resourcetype = resourcetype;
        this.childrenid = childrenid;
        this.address = address;
        this.password = password;
        this.password2 = password2;
        this.position = position;
        this.forumlogin = forumlogin;
        this.postnumber = postnumber;
        this.loginnumber = loginnumber;
        this.ekeyuser = ekeyuser;
        this.mainpage = mainpage;
        this.styleid = styleid;
        this.FIsout = FIsout;
        this.FIcon = FIcon;
        this.FDescription = FDescription;
        this.FName = FName;
        this.FNumber = FNumber;
        this.FContent = FContent;
        this.num = num;
        this.loginip = loginip;
        this.logintime = logintime;
        this.roles = roles;
    }

   
    // Property accessors

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getOrgid() {
        return this.orgid;
    }
    
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public String getRightid() {
        return this.rightid;
    }
    
    public void setRightid(String rightid) {
        this.rightid = rightid;
    }

    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }

    public String getParentid() {
        return this.parentid;
    }
    
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public String getFUsing() {
        return this.FUsing;
    }
    
    public void setFUsing(String FUsing) {
        this.FUsing = FUsing;
    }

    public String getOutuser() {
        return this.outuser;
    }
    
    public void setOutuser(String outuser) {
        this.outuser = outuser;
    }

    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getRepassword() {
        return this.repassword;
    }
    
    public void setRepassword(String repassword) {
        this.repassword = repassword;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getTemplatename() {
        return this.templatename;
    }
    
    public void setTemplatename(String templatename) {
        this.templatename = templatename;
    }

    public String getResourcetype() {
        return this.resourcetype;
    }
    
    public void setResourcetype(String resourcetype) {
        this.resourcetype = resourcetype;
    }

    public String getChildrenid() {
        return this.childrenid;
    }
    
    public void setChildrenid(String childrenid) {
        this.childrenid = childrenid;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword2() {
        return this.password2;
    }
    
    public void setPassword2(String password2) {
        this.password2 = password2;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getForumlogin() {
        return this.forumlogin;
    }
    
    public void setForumlogin(String forumlogin) {
        this.forumlogin = forumlogin;
    }

    public String getPostnumber() {
        return this.postnumber;
    }
    
    public void setPostnumber(String postnumber) {
        this.postnumber = postnumber;
    }

    public String getLoginnumber() {
        return this.loginnumber;
    }
    
    public void setLoginnumber(String loginnumber) {
        this.loginnumber = loginnumber;
    }

    public String getEkeyuser() {
        return this.ekeyuser;
    }
    
    public void setEkeyuser(String ekeyuser) {
        this.ekeyuser = ekeyuser;
    }

    public String getMainpage() {
        return this.mainpage;
    }
    
    public void setMainpage(String mainpage) {
        this.mainpage = mainpage;
    }

    public String getStyleid() {
        return this.styleid;
    }
    
    public void setStyleid(String styleid) {
        this.styleid = styleid;
    }

    public String getFIsout() {
        return this.FIsout;
    }
    
    public void setFIsout(String FIsout) {
        this.FIsout = FIsout;
    }

    public String getFIcon() {
        return this.FIcon;
    }
    
    public void setFIcon(String FIcon) {
        this.FIcon = FIcon;
    }

    public String getFDescription() {
        return this.FDescription;
    }
    
    public void setFDescription(String FDescription) {
        this.FDescription = FDescription;
    }

    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    public String getFNumber() {
        return this.FNumber;
    }
    
    public void setFNumber(String FNumber) {
        this.FNumber = FNumber;
    }

    public String getFContent() {
        return this.FContent;
    }
    
    public void setFContent(String FContent) {
        this.FContent = FContent;
    }

    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }

    public String getLoginip() {
        return this.loginip;
    }
    
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    public String getLogintime() {
        return this.logintime;
    }
    
    public void setLogintime(String logintime) {
        this.logintime = logintime;
    }

    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TUserId) ) return false;
		 TUserId castOther = ( TUserId ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getOrgid()==castOther.getOrgid()) || ( this.getOrgid()!=null && castOther.getOrgid()!=null && this.getOrgid().equals(castOther.getOrgid()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDeleted()==castOther.getDeleted()) || ( this.getDeleted()!=null && castOther.getDeleted()!=null && this.getDeleted().equals(castOther.getDeleted()) ) )
 && ( (this.getRightid()==castOther.getRightid()) || ( this.getRightid()!=null && castOther.getRightid()!=null && this.getRightid().equals(castOther.getRightid()) ) )
 && ( (this.getEname()==castOther.getEname()) || ( this.getEname()!=null && castOther.getEname()!=null && this.getEname().equals(castOther.getEname()) ) )
 && ( (this.getParentid()==castOther.getParentid()) || ( this.getParentid()!=null && castOther.getParentid()!=null && this.getParentid().equals(castOther.getParentid()) ) )
 && ( (this.getFUsing()==castOther.getFUsing()) || ( this.getFUsing()!=null && castOther.getFUsing()!=null && this.getFUsing().equals(castOther.getFUsing()) ) )
 && ( (this.getOutuser()==castOther.getOutuser()) || ( this.getOutuser()!=null && castOther.getOutuser()!=null && this.getOutuser().equals(castOther.getOutuser()) ) )
 && ( (this.getCname()==castOther.getCname()) || ( this.getCname()!=null && castOther.getCname()!=null && this.getCname().equals(castOther.getCname()) ) )
 && ( (this.getRepassword()==castOther.getRepassword()) || ( this.getRepassword()!=null && castOther.getRepassword()!=null && this.getRepassword().equals(castOther.getRepassword()) ) )
 && ( (this.getRemark()==castOther.getRemark()) || ( this.getRemark()!=null && castOther.getRemark()!=null && this.getRemark().equals(castOther.getRemark()) ) )
 && ( (this.getTemplatename()==castOther.getTemplatename()) || ( this.getTemplatename()!=null && castOther.getTemplatename()!=null && this.getTemplatename().equals(castOther.getTemplatename()) ) )
 && ( (this.getResourcetype()==castOther.getResourcetype()) || ( this.getResourcetype()!=null && castOther.getResourcetype()!=null && this.getResourcetype().equals(castOther.getResourcetype()) ) )
 && ( (this.getChildrenid()==castOther.getChildrenid()) || ( this.getChildrenid()!=null && castOther.getChildrenid()!=null && this.getChildrenid().equals(castOther.getChildrenid()) ) )
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) )
 && ( (this.getPassword()==castOther.getPassword()) || ( this.getPassword()!=null && castOther.getPassword()!=null && this.getPassword().equals(castOther.getPassword()) ) )
 && ( (this.getPassword2()==castOther.getPassword2()) || ( this.getPassword2()!=null && castOther.getPassword2()!=null && this.getPassword2().equals(castOther.getPassword2()) ) )
 && ( (this.getPosition()==castOther.getPosition()) || ( this.getPosition()!=null && castOther.getPosition()!=null && this.getPosition().equals(castOther.getPosition()) ) )
 && ( (this.getForumlogin()==castOther.getForumlogin()) || ( this.getForumlogin()!=null && castOther.getForumlogin()!=null && this.getForumlogin().equals(castOther.getForumlogin()) ) )
 && ( (this.getPostnumber()==castOther.getPostnumber()) || ( this.getPostnumber()!=null && castOther.getPostnumber()!=null && this.getPostnumber().equals(castOther.getPostnumber()) ) )
 && ( (this.getLoginnumber()==castOther.getLoginnumber()) || ( this.getLoginnumber()!=null && castOther.getLoginnumber()!=null && this.getLoginnumber().equals(castOther.getLoginnumber()) ) )
 && ( (this.getEkeyuser()==castOther.getEkeyuser()) || ( this.getEkeyuser()!=null && castOther.getEkeyuser()!=null && this.getEkeyuser().equals(castOther.getEkeyuser()) ) )
 && ( (this.getMainpage()==castOther.getMainpage()) || ( this.getMainpage()!=null && castOther.getMainpage()!=null && this.getMainpage().equals(castOther.getMainpage()) ) )
 && ( (this.getStyleid()==castOther.getStyleid()) || ( this.getStyleid()!=null && castOther.getStyleid()!=null && this.getStyleid().equals(castOther.getStyleid()) ) )
 && ( (this.getFIsout()==castOther.getFIsout()) || ( this.getFIsout()!=null && castOther.getFIsout()!=null && this.getFIsout().equals(castOther.getFIsout()) ) )
 && ( (this.getFIcon()==castOther.getFIcon()) || ( this.getFIcon()!=null && castOther.getFIcon()!=null && this.getFIcon().equals(castOther.getFIcon()) ) )
 && ( (this.getFDescription()==castOther.getFDescription()) || ( this.getFDescription()!=null && castOther.getFDescription()!=null && this.getFDescription().equals(castOther.getFDescription()) ) )
 && ( (this.getFName()==castOther.getFName()) || ( this.getFName()!=null && castOther.getFName()!=null && this.getFName().equals(castOther.getFName()) ) )
 && ( (this.getFNumber()==castOther.getFNumber()) || ( this.getFNumber()!=null && castOther.getFNumber()!=null && this.getFNumber().equals(castOther.getFNumber()) ) )
 && ( (this.getFContent()==castOther.getFContent()) || ( this.getFContent()!=null && castOther.getFContent()!=null && this.getFContent().equals(castOther.getFContent()) ) )
 && ( (this.getNum()==castOther.getNum()) || ( this.getNum()!=null && castOther.getNum()!=null && this.getNum().equals(castOther.getNum()) ) )
 && ( (this.getLoginip()==castOther.getLoginip()) || ( this.getLoginip()!=null && castOther.getLoginip()!=null && this.getLoginip().equals(castOther.getLoginip()) ) )
 && ( (this.getLogintime()==castOther.getLogintime()) || ( this.getLogintime()!=null && castOther.getLogintime()!=null && this.getLogintime().equals(castOther.getLogintime()) ) )
 && ( (this.getRoles()==castOther.getRoles()) || ( this.getRoles()!=null && castOther.getRoles()!=null && this.getRoles().equals(castOther.getRoles()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getOrgid() == null ? 0 : this.getOrgid().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDeleted() == null ? 0 : this.getDeleted().hashCode() );
         result = 37 * result + ( getRightid() == null ? 0 : this.getRightid().hashCode() );
         result = 37 * result + ( getEname() == null ? 0 : this.getEname().hashCode() );
         result = 37 * result + ( getParentid() == null ? 0 : this.getParentid().hashCode() );
         result = 37 * result + ( getFUsing() == null ? 0 : this.getFUsing().hashCode() );
         result = 37 * result + ( getOutuser() == null ? 0 : this.getOutuser().hashCode() );
         result = 37 * result + ( getCname() == null ? 0 : this.getCname().hashCode() );
         result = 37 * result + ( getRepassword() == null ? 0 : this.getRepassword().hashCode() );
         result = 37 * result + ( getRemark() == null ? 0 : this.getRemark().hashCode() );
         result = 37 * result + ( getTemplatename() == null ? 0 : this.getTemplatename().hashCode() );
         result = 37 * result + ( getResourcetype() == null ? 0 : this.getResourcetype().hashCode() );
         result = 37 * result + ( getChildrenid() == null ? 0 : this.getChildrenid().hashCode() );
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         result = 37 * result + ( getPassword() == null ? 0 : this.getPassword().hashCode() );
         result = 37 * result + ( getPassword2() == null ? 0 : this.getPassword2().hashCode() );
         result = 37 * result + ( getPosition() == null ? 0 : this.getPosition().hashCode() );
         result = 37 * result + ( getForumlogin() == null ? 0 : this.getForumlogin().hashCode() );
         result = 37 * result + ( getPostnumber() == null ? 0 : this.getPostnumber().hashCode() );
         result = 37 * result + ( getLoginnumber() == null ? 0 : this.getLoginnumber().hashCode() );
         result = 37 * result + ( getEkeyuser() == null ? 0 : this.getEkeyuser().hashCode() );
         result = 37 * result + ( getMainpage() == null ? 0 : this.getMainpage().hashCode() );
         result = 37 * result + ( getStyleid() == null ? 0 : this.getStyleid().hashCode() );
         result = 37 * result + ( getFIsout() == null ? 0 : this.getFIsout().hashCode() );
         result = 37 * result + ( getFIcon() == null ? 0 : this.getFIcon().hashCode() );
         result = 37 * result + ( getFDescription() == null ? 0 : this.getFDescription().hashCode() );
         result = 37 * result + ( getFName() == null ? 0 : this.getFName().hashCode() );
         result = 37 * result + ( getFNumber() == null ? 0 : this.getFNumber().hashCode() );
         result = 37 * result + ( getFContent() == null ? 0 : this.getFContent().hashCode() );
         result = 37 * result + ( getNum() == null ? 0 : this.getNum().hashCode() );
         result = 37 * result + ( getLoginip() == null ? 0 : this.getLoginip().hashCode() );
         result = 37 * result + ( getLogintime() == null ? 0 : this.getLogintime().hashCode() );
         result = 37 * result + ( getRoles() == null ? 0 : this.getRoles().hashCode() );
         return result;
   }   





}