package com.baosight.mode;

/**
 * AbstractVwXzxk generated by MyEclipse Persistence Tools
 */

public abstract class AbstractVwXzxk implements java.io.Serializable {

	// Fields

	private VwXzxkId id;

	// Constructors

	/** default constructor */
	public AbstractVwXzxk() {
	}

	/** full constructor */
	public AbstractVwXzxk(VwXzxkId id) {
		this.id = id;
	}

	// Property accessors

	public VwXzxkId getId() {
		return this.id;
	}

	public void setId(VwXzxkId id) {
		this.id = id;
	}

}