package com.baosight.mode;

/**
 * BsDatadictionary generated by MyEclipse Persistence Tools
 */

public class BsOther implements java.io.Serializable {

	// Fields
    private String id;
	
	private String name;

	private String username;

	private Long mobileNum;

	private String subjectname;

	private String duty;
	
	private String remark;
	
	private String infofeeType;

	// Constructors

	public String getInfofeeType() {
		return infofeeType;
	}

	public void setInfofeeType(String infofeeType) {
		this.infofeeType = infofeeType;
	}

	/** default constructor */
	public BsOther() {
	}

	/** full constructor */
	public BsOther(String id,String name,String username,Long mobileNum,String subjectname,String duty,String remark,String infofeeType) {
	 this.id = id;
	 this.name = name;
	 this.username = username;
	 this.mobileNum = mobileNum;
	 this.subjectname = subjectname;
	 this.duty = duty;
	 this.remark = remark;
	 this.infofeeType = infofeeType;
	}

	public Long getMobileNum() {
		return mobileNum;
	}

	public void setMobileNum(Long mobileNum) {
		this.mobileNum = mobileNum;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubjectname() {
		return subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDuty() {
		return duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}



	

	
}