package com.baosight.mode;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbArchives generated by MyEclipse Persistence Tools
 */

public class TbArchives implements java.io.Serializable {

	// Fields

	private String id;

	private String cateId;

	private String pubId;

	private String nopubdescId;

	private String formatId;

	private String typeId;

	private String topicId;

	private String applyId;

	private String title;

	private String fileId;

	private Date createTime;

	private String createDept;

	private String topic;

	private String category;

	private String pubclass;

	private String nopubdesc;

	private String abstract_;

	private String keywords;

	private String format;

	private String type;

	private String normalsign;

	private String draftsign;

	private String status;

	private String attachrealname;

	private String attachsysname;

	private String attr1;

	private String attr2;

	private String attr3;

	private String attr4;
	
	private String attr5;
	private Set<TbUploadFile> tbUploadFiles = new HashSet<TbUploadFile>(0);

	public void addTbUploadFile(TbUploadFile tbUploadFile){
		tbUploadFiles.add(tbUploadFile);
	}

	
	//	 Constructors
	/** default constructor */
	public TbArchives() {
	}

	/** full constructor */
	public TbArchives(String cateId, String pubId, String nopubdescId,
			String formatId, String typeId, String topicId, String applyId,
			String title, String fileId, Date createTime, String createDept,
			String topic, String category, String pubclass, String nopubdesc,
			String abstract_, String keywords, String format, String type,
			String normalsign, String draftsign, String status,
			String attachrealname, String attachsysname, String attr1,
			String attr2, Set tbUploadFiles,String attr3,
			String attr4,String attr5) {
		this.cateId = cateId;
		this.pubId = pubId;
		this.nopubdescId = nopubdescId;
		this.formatId = formatId;
		this.typeId = typeId;
		this.topicId = topicId;
		this.applyId = applyId;
		this.title = title;
		this.fileId = fileId;
		this.createTime = createTime;
		this.createDept = createDept;
		this.topic = topic;
		this.category = category;
		this.pubclass = pubclass;
		this.nopubdesc = nopubdesc;
		this.abstract_ = abstract_;
		this.keywords = keywords;
		this.format = format;
		this.type = type;
		this.normalsign = normalsign;
		this.draftsign = draftsign;
		this.status = status;
		this.attachrealname = attachrealname;
		this.attachsysname = attachsysname;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.attr5 = attr5;
		this.tbUploadFiles = tbUploadFiles;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCateId() {
		return this.cateId;
	}

	public void setCateId(String cateId) {
		this.cateId = cateId;
	}

	public String getPubId() {
		return this.pubId;
	}

	public void setPubId(String pubId) {
		this.pubId = pubId;
	}

	public String getNopubdescId() {
		return this.nopubdescId;
	}

	public void setNopubdescId(String nopubdescId) {
		this.nopubdescId = nopubdescId;
	}

	public String getFormatId() {
		return this.formatId;
	}

	public void setFormatId(String formatId) {
		this.formatId = formatId;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public String getTopicId() {
		return this.topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	public String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateDept() {
		return this.createDept;
	}

	public void setCreateDept(String createDept) {
		this.createDept = createDept;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getPubclass() {
		return this.pubclass;
	}

	public void setPubclass(String pubclass) {
		this.pubclass = pubclass;
	}

	public String getNopubdesc() {
		return this.nopubdesc;
	}

	public void setNopubdesc(String nopubdesc) {
		this.nopubdesc = nopubdesc;
	}

	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNormalsign() {
		return this.normalsign;
	}

	public void setNormalsign(String normalsign) {
		this.normalsign = normalsign;
	}

	public String getDraftsign() {
		return this.draftsign;
	}

	public void setDraftsign(String draftsign) {
		this.draftsign = draftsign;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAttachrealname() {
		return this.attachrealname;
	}

	public void setAttachrealname(String attachrealname) {
		this.attachrealname = attachrealname;
	}

	public String getAttachsysname() {
		return this.attachsysname;
	}

	public void setAttachsysname(String attachsysname) {
		this.attachsysname = attachsysname;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public Set getTbUploadFiles() {
		return this.tbUploadFiles;
	}

	public void setTbUploadFiles(Set tbUploadFiles) {
		this.tbUploadFiles = tbUploadFiles;
	}


	public String getAttr3() {
		return attr3;
	}


	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}


	public String getAttr4() {
		return attr4;
	}


	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}


	public String getAttr5() {
		return attr5;
	}


	public void setAttr5(String attr5) {
		this.attr5 = attr5;
	}

}