package com.baosight.mode;

/**
 * TbDocsendSubject generated by MyEclipse Persistence Tools
 */

public class TbDocsendSubject implements java.io.Serializable {

	// Fields

	private String id;

	private Long style;

	private Long class_;

	private String title;

	private String pinyin;

	// Constructors

	/** default constructor */
	public TbDocsendSubject() {
	}

	/** minimal constructor */
	public TbDocsendSubject(Long style, Long class_, String title) {
		this.style = style;
		this.class_ = class_;
		this.title = title;
	}

	/** full constructor */
	public TbDocsendSubject(Long style, Long class_, String title, String pinyin) {
		this.style = style;
		this.class_ = class_;
		this.title = title;
		this.pinyin = pinyin;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getStyle() {
		return this.style;
	}

	public void setStyle(Long style) {
		this.style = style;
	}

	public Long getClass_() {
		return this.class_;
	}

	public void setClass_(Long class_) {
		this.class_ = class_;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

}