package com.baosight.mode;

import java.util.Date;

/**
 * TbDocUrgent generated by MyEclipse Persistence Tools
 */

public class TbDocUrgent implements java.io.Serializable {

	// Fields

	private String id;

	private String urgentCon;

	private String urgentObj;

	private Date urgentTime;

	private String urgentWay;

	private Date selectTime;

	private String attr1;

	private String attr2;

	// Constructors

	/** default constructor */
	public TbDocUrgent() {
	}

	/** full constructor */
	public TbDocUrgent(String urgentCon, String urgentObj, Date urgentTime,
			String urgentWay, Date selectTime, String attr1, String attr2) {
		this.urgentCon = urgentCon;
		this.urgentObj = urgentObj;
		this.urgentTime = urgentTime;
		this.urgentWay = urgentWay;
		this.selectTime = selectTime;
		this.attr1 = attr1;
		this.attr2 = attr2;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUrgentCon() {
		return this.urgentCon;
	}

	public void setUrgentCon(String urgentCon) {
		this.urgentCon = urgentCon;
	}

	public String getUrgentObj() {
		return this.urgentObj;
	}

	public void setUrgentObj(String urgentObj) {
		this.urgentObj = urgentObj;
	}

	public Date getUrgentTime() {
		return this.urgentTime;
	}

	public void setUrgentTime(Date urgentTime) {
		this.urgentTime = urgentTime;
	}

	public String getUrgentWay() {
		return this.urgentWay;
	}

	public void setUrgentWay(String urgentWay) {
		this.urgentWay = urgentWay;
	}

	public Date getSelectTime() {
		return this.selectTime;
	}

	public void setSelectTime(Date selectTime) {
		this.selectTime = selectTime;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

}