package com.baosight.mode;

import java.util.Date;

/**
 * TbDocArchiveCode generated by MyEclipse Persistence Tools
 */

public class TbDocArchiveCode implements java.io.Serializable {

	// Fields

	private String id;

	private String sn;

	private String name;

	private String description;

	private String categoryId;

	private String year;

	private Date beginDate;

	private Date endDate;

	private Long pageCount;

	private Long pageSize;

	private String keepTime;

	private String parentId;

	private Long seq;

	private String sysAttr;

	private String status;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbDocArchiveCode() {
	}

	/** minimal constructor */
	public TbDocArchiveCode(String sn, String name, String year,
			Long pageCount, Long pageSize, Long seq, String status) {
		this.sn = sn;
		this.name = name;
		this.year = year;
		this.pageCount = pageCount;
		this.pageSize = pageSize;
		this.seq = seq;
		this.status = status;
	}

	/** full constructor */
	public TbDocArchiveCode(String sn, String name, String description,
			String categoryId, String year, Date beginDate, Date endDate,
			Long pageCount, Long pageSize, String keepTime, String parentId,
			Long seq, String sysAttr, String status, String attr1,
			String attr2, String attr3) {
		this.sn = sn;
		this.name = name;
		this.description = description;
		this.categoryId = categoryId;
		this.year = year;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.pageCount = pageCount;
		this.pageSize = pageSize;
		this.keepTime = keepTime;
		this.parentId = parentId;
		this.seq = seq;
		this.sysAttr = sysAttr;
		this.status = status;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Long getPageCount() {
		return this.pageCount;
	}

	public void setPageCount(Long pageCount) {
		this.pageCount = pageCount;
	}

	public Long getPageSize() {
		return this.pageSize;
	}

	public void setPageSize(Long pageSize) {
		this.pageSize = pageSize;
	}

	public String getKeepTime() {
		return this.keepTime;
	}

	public void setKeepTime(String keepTime) {
		this.keepTime = keepTime;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	public String getSysAttr() {
		return this.sysAttr;
	}

	public void setSysAttr(String sysAttr) {
		this.sysAttr = sysAttr;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}