package com.baosight.mode;

/**
 * TbDocInfoLevelSeq generated by MyEclipse Persistence Tools
 */

public class TbDocInfoLevelSeq implements java.io.Serializable {

	// Fields

	private TbDocInfoLevelSeqId id;

	private String name;

	private Long curruntNum;

	// Constructors

	/** default constructor */
	public TbDocInfoLevelSeq() {
	}

	/** minimal constructor */
	public TbDocInfoLevelSeq(TbDocInfoLevelSeqId id, Long curruntNum) {
		this.id = id;
		this.curruntNum = curruntNum;
	}

	/** full constructor */
	public TbDocInfoLevelSeq(TbDocInfoLevelSeqId id, String name,
			Long curruntNum) {
		this.id = id;
		this.name = name;
		this.curruntNum = curruntNum;
	}

	// Property accessors

	public TbDocInfoLevelSeqId getId() {
		return this.id;
	}

	public void setId(TbDocInfoLevelSeqId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getCurruntNum() {
		return this.curruntNum;
	}

	public void setCurruntNum(Long curruntNum) {
		this.curruntNum = curruntNum;
	}

}