package com.baosight.mode;

/**
 * TbDocInfoLevelSeqId generated by MyEclipse Persistence Tools
 */

public class TbDocInfoLevelSeqId implements java.io.Serializable {

	// Fields

	private String code;

	private String codeYear;

	// Constructors

	/** default constructor */
	public TbDocInfoLevelSeqId() {
	}

	/** full constructor */
	public TbDocInfoLevelSeqId(String code, String codeYear) {
		this.code = code;
		this.codeYear = codeYear;
	}

	// Property accessors

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeYear() {
		return this.codeYear;
	}

	public void setCodeYear(String codeYear) {
		this.codeYear = codeYear;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDocInfoLevelSeqId))
			return false;
		TbDocInfoLevelSeqId castOther = (TbDocInfoLevelSeqId) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& ((this.getCodeYear() == castOther.getCodeYear()) || (this
						.getCodeYear() != null
						&& castOther.getCodeYear() != null && this
						.getCodeYear().equals(castOther.getCodeYear())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getCodeYear() == null ? 0 : this.getCodeYear().hashCode());
		return result;
	}

}