package com.baosight.mode;

/**
 * TbFilesendAttachment generated by MyEclipse Persistence Tools
 */

public class TbFilesendAttachment implements java.io.Serializable {

	// Fields

	private String id;

	private TbFilesend tbFilesend;

	private String originallyName;

	private String serverName;

	// Constructors

	/** default constructor */
	public TbFilesendAttachment() {
	}

	/** full constructor */
	public TbFilesendAttachment(TbFilesend tbFilesend, String originallyName,
			String serverName) {
		this.tbFilesend = tbFilesend;
		this.originallyName = originallyName;
		this.serverName = serverName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbFilesend getTbFilesend() {
		return this.tbFilesend;
	}

	public void setTbFilesend(TbFilesend tbFilesend) {
		this.tbFilesend = tbFilesend;
	}

	public String getOriginallyName() {
		return this.originallyName;
	}

	public void setOriginallyName(String originallyName) {
		this.originallyName = originallyName;
	}

	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

}