package com.baosight.mode;

import java.util.Date;

/**
 * TbGovInfoPub generated by MyEclipse Persistence Tools
 */

public class TbGovInfoPub implements java.io.Serializable {

	// Fields

	private String id;

	private String applyId;

	private String applicant;

	private String fileId;

	private String descr;

	private String reason;

	private Date startTime;

	private Date endTime;

	private String offerWay;

	private String passWay;

	private String applyManner;

	private String primaryConManner;

	private String applyAddr;

	private String phone;

	private String email;

	private String cellPhone;

	private String applyType;

	private String certType;

	private String certNo;

	private String attr1;

	private String attr2;

	private String attr3;

	private String attr4;

	private Long fee;

	private String postcode;

	private String docName;

	private String docNum;

	private String companyName;
	
	private com.baosight.mode.TbGovInfoPubAudit tbGovInfoPubAudit;
	public com.baosight.mode.TbGovInfoPubAudit getTbGovInfoPubAudit() {
		return tbGovInfoPubAudit;
	}

	public void setTbGovInfoPubAudit(
			com.baosight.mode.TbGovInfoPubAudit tbGovInfoPubAudit) {
		this.tbGovInfoPubAudit = tbGovInfoPubAudit;
	}

	/** default constructor */
	public TbGovInfoPub() {
	}

	/** full constructor */
	public TbGovInfoPub(String applyId, String applicant, String fileId,
			String descr, String reason, Date startTime, Date endTime,
			String offerWay, String passWay, String applyManner,
			String primaryConManner, String applyAddr, String phone,
			String email, String cellPhone, String applyType, String certType,
			String certNo, String attr1, String attr2, String attr3,
			String attr4,Long fee) {
		this.applyId = applyId;
		this.applicant = applicant;
		this.fileId = fileId;
		this.descr = descr;
		this.reason = reason;
		this.startTime = startTime;
		this.endTime = endTime;
		this.offerWay = offerWay;
		this.passWay = passWay;
		this.applyManner = applyManner;
		this.primaryConManner = primaryConManner;
		this.applyAddr = applyAddr;
		this.phone = phone;
		this.email = email;
		this.cellPhone = cellPhone;
		this.applyType = applyType;
		this.certType = certType;
		this.certNo = certNo;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.fee =fee;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getOfferWay() {
		return this.offerWay;
	}

	public void setOfferWay(String offerWay) {
		this.offerWay = offerWay;
	}

	public String getPassWay() {
		return this.passWay;
	}

	public void setPassWay(String passWay) {
		this.passWay = passWay;
	}

	public String getApplyManner() {
		return this.applyManner;
	}

	public void setApplyManner(String applyManner) {
		this.applyManner = applyManner;
	}

	public String getPrimaryConManner() {
		return this.primaryConManner;
	}

	public void setPrimaryConManner(String primaryConManner) {
		this.primaryConManner = primaryConManner;
	}

	public String getApplyAddr() {
		return this.applyAddr;
	}

	public void setApplyAddr(String applyAddr) {
		this.applyAddr = applyAddr;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getApplyType() {
		return this.applyType;
	}

	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	public String getCertNo() {
		return this.certNo;
	}

	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	public Long getFee() {
		return fee;
	}

	public void setFee(Long fee) {
		this.fee = fee;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getDocName() {
		return docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	public String getDocNum() {
		return docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	
	

}