package com.baosight.mode;

import java.sql.Clob;
import java.util.Date;

/**
 * TbInfoPubContent generated by MyEclipse Persistence Tools
 */

public class TbInfoPubContent implements java.io.Serializable {

	// Fields

	private String id;

	private String infoId;

	private String infoSource;

	private String title;

	private String authorName;

	private String keyword;

	private Date createTime;

	private Date publishTime;

	private String publishFlag;

	private Long sendTo;

	private String infoSubject;

	private String attr1;

	private String attr2;

	private String attr3;

	private Date recordTime;

	private Clob content;

	private String summaryTitle;

	private String summary;

	private String titleColor;

	private Long iscopyright;

	private Date topTime;
	
	private String infoType;
	
	private String col0V;
	
	private String col1V;
	
	private String col2V;
	
	private String col3V;
	
	private String col4V;
	
	private String col5V;
	
	private String col6V;
	
	private String col7V;
	
	private String col8V;
	
	private String addType;
	

	// Constructors

	/** default constructor */
	public TbInfoPubContent() {
	}

	/** full constructor */
	public TbInfoPubContent(String infoId, String infoSource, String title,
			String authorName, String keyword, Date createTime,
			Date publishTime, String publishFlag, Long sendTo,
			String infoSubject, String attr1, String attr2, String attr3,
			Date recordTime, Clob content, String summaryTitle,
			String summary, String titleColor, Long iscopyright, Date topTime,String infoType,String addType,
			String col0V,String col1V,String col2V,String col3V,String col4V,String col5V,String col6V,
			String col7V,String col8V) {
		this.infoId = infoId;
		this.infoSource = infoSource;
		this.title = title;
		this.authorName = authorName;
		this.keyword = keyword;
		this.createTime = createTime;
		this.publishTime = publishTime;
		this.publishFlag = publishFlag;
		this.sendTo = sendTo;
		this.infoSubject = infoSubject;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.recordTime = recordTime;
		this.content = content;
		this.summaryTitle = summaryTitle;
		this.summary = summary;
		this.titleColor = titleColor;
		this.iscopyright = iscopyright;
		this.topTime = topTime;
		this.infoType = infoType;
		this.addType = addType;
		this.col0V = col0V;
		this.col1V = col1V;
		this.col2V = col2V;
		this.col3V = col3V;
		this.col4V = col4V;
		this.col5V = col5V;
		this.col6V = col6V;
		this.col7V = col7V;
		this.col8V = col8V;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getInfoSource() {
		return this.infoSource;
	}

	public void setInfoSource(String infoSource) {
		this.infoSource = infoSource;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getPublishFlag() {
		return this.publishFlag;
	}

	public void setPublishFlag(String publishFlag) {
		this.publishFlag = publishFlag;
	}

	public Long getSendTo() {
		return this.sendTo;
	}

	public void setSendTo(Long sendTo) {
		this.sendTo = sendTo;
	}

	public String getInfoSubject() {
		return this.infoSubject;
	}

	public void setInfoSubject(String infoSubject) {
		this.infoSubject = infoSubject;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public Clob getContent() {
		return this.content;
	}

	public void setContent(Clob content) {
		this.content = content;
	}

	public String getSummaryTitle() {
		return this.summaryTitle;
	}

	public void setSummaryTitle(String summaryTitle) {
		this.summaryTitle = summaryTitle;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getTitleColor() {
		return this.titleColor;
	}

	public void setTitleColor(String titleColor) {
		this.titleColor = titleColor;
	}

	public Long getIscopyright() {
		return this.iscopyright;
	}

	public void setIscopyright(Long iscopyright) {
		this.iscopyright = iscopyright;
	}

	public Date getTopTime() {
		return this.topTime;
	}

	public void setTopTime(Date topTime) {
		this.topTime = topTime;
	}

	public String getInfoType() {
		return infoType;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getCol0V() {
		return col0V;
	}

	public void setCol0V(String col0V) {
		this.col0V = col0V;
	}

	public String getCol1V() {
		return col1V;
	}

	public void setCol1V(String col1V) {
		this.col1V = col1V;
	}

	public String getCol2V() {
		return col2V;
	}

	public void setCol2V(String col2V) {
		this.col2V = col2V;
	}

	public String getCol3V() {
		return col3V;
	}

	public void setCol3V(String col3V) {
		this.col3V = col3V;
	}

	public String getCol4V() {
		return col4V;
	}

	public void setCol4V(String col4V) {
		this.col4V = col4V;
	}

	public String getCol5V() {
		return col5V;
	}

	public void setCol5V(String col5V) {
		this.col5V = col5V;
	}

	public String getCol6V() {
		return col6V;
	}

	public void setCol6V(String col6V) {
		this.col6V = col6V;
	}

	public String getCol7V() {
		return col7V;
	}

	public void setCol7V(String col7V) {
		this.col7V = col7V;
	}

	public String getCol8V() {
		return col8V;
	}

	public void setCol8V(String col8V) {
		this.col8V = col8V;
	}

	public String getAddType() {
		return addType;
	}

	public void setAddType(String addType) {
		this.addType = addType;
	}
}