package com.baosight.mode;

import java.util.Date;

/**
 * TbInfoPubCla generated by MyEclipse Persistence Tools
 */

public class TbInfoPubCla implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String code;

	private String parentid;

	private Date createTime;

	private Long defOrder;

	private Long onlyTree;

	private Long enable;

	private String rem;

	private String attr1;

	private String attr2;

	private String attr3;

	private String attr4;
	
	private Integer node;
	// Constructors

	/** default constructor */
	public TbInfoPubCla() {
	}

	/** full constructor */
	public TbInfoPubCla(String name, String code, String parentid,
			Date createTime, Long defOrder,Long onlyTree, Long enable,
			String rem) {
		this.name = name;
		this.code = code;
		this.parentid = parentid;
		this.defOrder = defOrder;
		this.createTime = createTime;
		
		this.onlyTree = onlyTree;
		this.enable = enable;
		this.rem = rem;
	
	}
	
	public TbInfoPubCla(String name, String code, String parentid,
			Date createTime, Long defOrder, Long onlyTree, Long enable,
			String rem, String attr1, String attr2, String attr3, String attr4) {
		this.name = name;
		this.code = code;
		this.parentid = parentid;
		this.createTime = createTime;
		this.defOrder = defOrder;
		this.onlyTree = onlyTree;
		this.enable = enable;
		this.rem = rem;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getDefOrder() {
		return this.defOrder;
	}

	public void setDefOrder(Long defOrder) {
		this.defOrder = defOrder;
	}

	public Long getOnlyTree() {
		return this.onlyTree;
	}

	public void setOnlyTree(Long onlyTree) {
		this.onlyTree = onlyTree;
	}

	public Long getEnable() {
		return this.enable;
	}

	public void setEnable(Long enable) {
		this.enable = enable;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(String attr4) {
		this.attr4 = attr4;
	}

	public Integer getNode() {
		return node;
	}

	public void setNode(Integer node) {
		this.node = node;
	}

}