package com.baosight.mode;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TbMeetingrecord generated by MyEclipse Persistence Tools
 */
public class TbMeetingrecord implements java.io.Serializable {

	private String id;

	private String meetingrecordTitle;

	private Date meetingrecordTime;

	private String meetingrecordName;

	private String meetingrecordAdv;

	private String meetingrecordRem;

	private String meetingrecordJoiner;

	private String meetingrecordStatus;

	private String attr1;

	private String attr2;

	private String attr3;

	/** default constructor */
	public TbMeetingrecord() {
	}

	/** full constructor */
	public TbMeetingrecord(String meetingrecordTitle, Date meetingrecordTime,
			String meetingrecordName, String meetingrecordAdv,
			String meetingrecordRem, String meetingrecordJoiner,
			String meetingrecordStatus, String attr1, String attr2, String attr3) {
		this.meetingrecordTitle = meetingrecordTitle;
		this.meetingrecordTime = meetingrecordTime;
		this.meetingrecordName = meetingrecordName;
		this.meetingrecordAdv = meetingrecordAdv;
		this.meetingrecordRem = meetingrecordRem;
		this.meetingrecordJoiner = meetingrecordJoiner;
		this.meetingrecordStatus = meetingrecordStatus;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;

	}

	public String getAttr1() {
		return attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMeetingrecordAdv() {
		return meetingrecordAdv;
	}

	public void setMeetingrecordAdv(String meetingrecordAdv) {
		this.meetingrecordAdv = meetingrecordAdv;
	}

	public String getMeetingrecordJoiner() {
		return meetingrecordJoiner;
	}

	public void setMeetingrecordJoiner(String meetingrecordJoiner) {
		this.meetingrecordJoiner = meetingrecordJoiner;
	}

	public String getMeetingrecordName() {
		return meetingrecordName;
	}

	public void setMeetingrecordName(String meetingrecordName) {
		this.meetingrecordName = meetingrecordName;
	}

	public String getMeetingrecordRem() {
		return meetingrecordRem;
	}

	public void setMeetingrecordRem(String meetingrecordRem) {
		this.meetingrecordRem = meetingrecordRem;
	}

	public String getMeetingrecordStatus() {
		return meetingrecordStatus;
	}

	public void setMeetingrecordStatus(String meetingrecordStatus) {
		this.meetingrecordStatus = meetingrecordStatus;
	}

	public Date getMeetingrecordTime() {
		return meetingrecordTime;
	}

	public void setMeetingrecordTime(Date meetingrecordTime) {
		this.meetingrecordTime = meetingrecordTime;
	}

	public String getMeetingrecordTitle() {
		return meetingrecordTitle;
	}

	public void setMeetingrecordTitle(String meetingrecordTitle) {
		this.meetingrecordTitle = meetingrecordTitle;
	}

}
