package com.baosight.mode;

import java.util.Date;

/**
 * TbOaSmsSchedule generated by MyEclipse Persistence Tools
 */

public class TbOaSmsSchedule implements java.io.Serializable {

	// Fields

	private String id;

	private Date scheduletime;

	private String userid;

	private String destNumber;

	private String messageContent;

	private String systype;

	private String flag;

	private String departid;

	private String senduserid;

	private String senddepartid;

	private String bz;

	// Constructors

	/** default constructor */
	public TbOaSmsSchedule() {
	}

	/** full constructor */
	public TbOaSmsSchedule(Date scheduletime, String userid, String destNumber,
			String messageContent, String systype, String flag,
			String departid, String senduserid, String senddepartid, String bz) {
		this.scheduletime = scheduletime;
		this.userid = userid;
		this.destNumber = destNumber;
		this.messageContent = messageContent;
		this.systype = systype;
		this.flag = flag;
		this.departid = departid;
		this.senduserid = senduserid;
		this.senddepartid = senddepartid;
		this.bz = bz;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getScheduletime() {
		return this.scheduletime;
	}

	public void setScheduletime(Date scheduletime) {
		this.scheduletime = scheduletime;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getDestNumber() {
		return this.destNumber;
	}

	public void setDestNumber(String destNumber) {
		this.destNumber = destNumber;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public String getSystype() {
		return this.systype;
	}

	public void setSystype(String systype) {
		this.systype = systype;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getDepartid() {
		return this.departid;
	}

	public void setDepartid(String departid) {
		this.departid = departid;
	}

	public String getSenduserid() {
		return this.senduserid;
	}

	public void setSenduserid(String senduserid) {
		this.senduserid = senduserid;
	}

	public String getSenddepartid() {
		return this.senddepartid;
	}

	public void setSenddepartid(String senddepartid) {
		this.senddepartid = senddepartid;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}