package com.baosight.mode;

/**
 * TbPstlvl generated by MyEclipse Persistence Tools
 */

public class TbPstlvl implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String code;

	// Constructors

	/** default constructor */
	public TbPstlvl() {
	}

	/** full constructor */
	public TbPstlvl(String name, String code) {
		this.name = name;
		this.code = code;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}