package com.baosight.mode;

import java.util.Date;

/**
 * TbReply7 generated by MyEclipse Persistence Tools
 */

public class TbReply7 implements java.io.Serializable {

	// Fields

	private String id;

	private String applicant;

	private String year;

	private String applyNo;

	private Date applyDate;

	private String applyTitle;

	private String replyType;

	private String offerWay;

	private Date signDate;

	private String attr1;

	private String attr2;

	private String attr3;

	// Constructors

	/** default constructor */
	public TbReply7() {
	}

	/** full constructor */
	public TbReply7(String applicant, String year, String applyNo,
			Date applyDate, String applyTitle, String replyType,
			String offerWay, Date signDate, String attr1, String attr2,
			String attr3) {
		this.applicant = applicant;
		this.year = year;
		this.applyNo = applyNo;
		this.applyDate = applyDate;
		this.applyTitle = applyTitle;
		this.replyType = replyType;
		this.offerWay = offerWay;
		this.signDate = signDate;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(String applyNo) {
		this.applyNo = applyNo;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getApplyTitle() {
		return this.applyTitle;
	}

	public void setApplyTitle(String applyTitle) {
		this.applyTitle = applyTitle;
	}

	public String getReplyType() {
		return this.replyType;
	}

	public void setReplyType(String replyType) {
		this.replyType = replyType;
	}

	public String getOfferWay() {
		return this.offerWay;
	}

	public void setOfferWay(String offerWay) {
		this.offerWay = offerWay;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

}