package com.baosight.mode;

/**
 * TbRoleAuth generated by MyEclipse Persistence Tools
 */

public class TbRoleAuth implements java.io.Serializable {

	// Fields

	private String id;

	private String roleid;

	private String authid;

	// Constructors

	/** default constructor */
	public TbRoleAuth() {
	}

	/** full constructor */
	public TbRoleAuth(String roleid, String authid) {
		this.roleid = roleid;
		this.authid = authid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getAuthid() {
		return this.authid;
	}

	public void setAuthid(String authid) {
		this.authid = authid;
	}

}