package com.baosight.mode;

/**
 * TbSmsUser generated by MyEclipse Persistence Tools
 */

public class TbSmsUser implements java.io.Serializable {

	// Fields

	private String id;

	private String username;

	private String userpasswd;

	private String departid;

	private String usertype;

	private String remark;

	private String bmType;

	private String realname;

	private String usersort;

	// Constructors

	/** default constructor */
	public TbSmsUser() {
	}

	/** full constructor */
	public TbSmsUser(String username, String userpasswd, String departid,
			String usertype, String remark, String bmType, String realname,
			String usersort) {
		this.username = username;
		this.userpasswd = userpasswd;
		this.departid = departid;
		this.usertype = usertype;
		this.remark = remark;
		this.bmType = bmType;
		this.realname = realname;
		this.usersort = usersort;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpasswd() {
		return this.userpasswd;
	}

	public void setUserpasswd(String userpasswd) {
		this.userpasswd = userpasswd;
	}

	public String getDepartid() {
		return this.departid;
	}

	public void setDepartid(String departid) {
		this.departid = departid;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getBmType() {
		return this.bmType;
	}

	public void setBmType(String bmType) {
		this.bmType = bmType;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getUsersort() {
		return this.usersort;
	}

	public void setUsersort(String usersort) {
		this.usersort = usersort;
	}

}