package com.baosight.mode;

/**
 * TbSmsSubject generated by MyEclipse Persistence Tools
 */

public class TbSmsSubject implements java.io.Serializable {

	// Fields

	private String id;

	private String subject;

	private String feetypeId;

	private String infoType;

	private String schedule;

	private String jjsw;

	private String bz;

	// Constructors

	/** default constructor */
	public TbSmsSubject() {
	}

	/** full constructor */
	public TbSmsSubject(String subject, String feetypeId, String infoType,
			String schedule, String jjsw, String bz) {
		this.subject = subject;
		this.feetypeId = feetypeId;
		this.infoType = infoType;
		this.schedule = schedule;
		this.jjsw = jjsw;
		this.bz = bz;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getFeetypeId() {
		return this.feetypeId;
	}

	public void setFeetypeId(String feetypeId) {
		this.feetypeId = feetypeId;
	}

	public String getInfoType() {
		return this.infoType;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	public String getJjsw() {
		return this.jjsw;
	}

	public void setJjsw(String jjsw) {
		this.jjsw = jjsw;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}