package com.baosight.mode;

import java.util.Date;

/**
 * TbSwrx generated by MyEclipse Persistence Tools
 */

public class TbSwrx implements java.io.Serializable {

	// Fields

	private Long swrxid;

	private String swrxno;

	private String acceptedunits;

	private Long tracknum;

	private Long returnvisitnum;

	private String statementsmark;

	private String trackingtags;

	private String cqcfbx;

	private Date informationreliability;

	private Date autoprinttime;

	private Date firstautoprinttime;

	private String stationtomark;

	private Date underordertime;

	private Date recevicereporttime;

	private String logonstation;

	private String reflectpeople;

	private String customerno;

	private String reflectunit;

	private String reflectphone;

	private String reflectdistrict;

	private String addresshappen;

	private Date datehappen;

	private String reflecttype;

	private String reflectcontent;

	private String cljb;

	private String reflectforms;

	private String reflectsour;

	private String acceptedremarks;

	private String remarklogonuser;

	private Date completiontime;

	private String dealpople;

	private String dealtype;

	private String dealcontent;

	private String cause;

	private String solutions;

	private String dealresult;

	private String dealistimely;

	private String dealremarks;

	private String repeatsigns;

	private String repeatrecords;

	private String deallogonuser;

	private String trackingprogram;

	private String mobilephone;

	private String email;

	private String reflectindustry;

	private Date appointmenttime;

	private Date inputdate;

	private String sellitemsistimely;

	private Date verifytime;

	private String taskno;

	private String replyornot;

	private String verifylogonuser;

	private String verifypeople;

	private String verifyremarks;

	private String verifytimelyrate;

	private String isreview;

	private String acceptedstatus;

	private Date acceptedtime;

	private String replylogonuser;

	private Date replytime;

	private String replyforms;

	private String replyremarks;

	private String verifyresult;

	private String no12319;

	private String oldsystemno;

	private String status12319;
	
	private String status;
	
	private String attr1;
	
	private String attr2;
	
	private String attr3;

	// Constructors

	/** default constructor */
	public TbSwrx() {
	}

	/** minimal constructor */
	public TbSwrx(String swrxno) {
		this.swrxno = swrxno;
	}

	/** full constructor */
	public TbSwrx(String swrxno, String acceptedunits, Long tracknum,
			Long returnvisitnum, String statementsmark, String trackingtags,
			String cqcfbx, Date informationreliability, Date autoprinttime,
			Date firstautoprinttime, String stationtomark, Date underordertime,
			Date recevicereporttime, String logonstation, String reflectpeople,
			String customerno, String reflectunit, String reflectphone,
			String reflectdistrict, String addresshappen, Date datehappen,
			String reflecttype, String reflectcontent, String cljb,
			String reflectforms, String reflectsour, String acceptedremarks,
			String remarklogonuser, Date completiontime, String dealpople,
			String dealtype, String dealcontent, String cause,
			String solutions, String dealresult, String dealistimely,
			String dealremarks, String repeatsigns, String repeatrecords,
			String deallogonuser, String trackingprogram, String mobilephone,
			String email, String reflectindustry, Date appointmenttime,
			Date inputdate, String sellitemsistimely, Date verifytime,
			String taskno, String replyornot, String verifylogonuser,
			String verifypeople, String verifyremarks, String verifytimelyrate,
			String isreview, String acceptedstatus, Date acceptedtime,
			String replylogonuser, Date replytime, String replyforms,
			String replyremarks, String verifyresult, String no12319,
			String oldsystemno, String status12319,String status,String attr1,String attr2,String attr3) {
		this.swrxno = swrxno;
		this.acceptedunits = acceptedunits;
		this.tracknum = tracknum;
		this.returnvisitnum = returnvisitnum;
		this.statementsmark = statementsmark;
		this.trackingtags = trackingtags;
		this.cqcfbx = cqcfbx;
		this.informationreliability = informationreliability;
		this.autoprinttime = autoprinttime;
		this.firstautoprinttime = firstautoprinttime;
		this.stationtomark = stationtomark;
		this.underordertime = underordertime;
		this.recevicereporttime = recevicereporttime;
		this.logonstation = logonstation;
		this.reflectpeople = reflectpeople;
		this.customerno = customerno;
		this.reflectunit = reflectunit;
		this.reflectphone = reflectphone;
		this.reflectdistrict = reflectdistrict;
		this.addresshappen = addresshappen;
		this.datehappen = datehappen;
		this.reflecttype = reflecttype;
		this.reflectcontent = reflectcontent;
		this.cljb = cljb;
		this.reflectforms = reflectforms;
		this.reflectsour = reflectsour;
		this.acceptedremarks = acceptedremarks;
		this.remarklogonuser = remarklogonuser;
		this.completiontime = completiontime;
		this.dealpople = dealpople;
		this.dealtype = dealtype;
		this.dealcontent = dealcontent;
		this.cause = cause;
		this.solutions = solutions;
		this.dealresult = dealresult;
		this.dealistimely = dealistimely;
		this.dealremarks = dealremarks;
		this.repeatsigns = repeatsigns;
		this.repeatrecords = repeatrecords;
		this.deallogonuser = deallogonuser;
		this.trackingprogram = trackingprogram;
		this.mobilephone = mobilephone;
		this.email = email;
		this.reflectindustry = reflectindustry;
		this.appointmenttime = appointmenttime;
		this.inputdate = inputdate;
		this.sellitemsistimely = sellitemsistimely;
		this.verifytime = verifytime;
		this.taskno = taskno;
		this.replyornot = replyornot;
		this.verifylogonuser = verifylogonuser;
		this.verifypeople = verifypeople;
		this.verifyremarks = verifyremarks;
		this.verifytimelyrate = verifytimelyrate;
		this.isreview = isreview;
		this.acceptedstatus = acceptedstatus;
		this.acceptedtime = acceptedtime;
		this.replylogonuser = replylogonuser;
		this.replytime = replytime;
		this.replyforms = replyforms;
		this.replyremarks = replyremarks;
		this.verifyresult = verifyresult;
		this.no12319 = no12319;
		this.oldsystemno = oldsystemno;
		this.status12319 = status12319;
		this.status=status;
		this.attr1=attr1;
		this.attr2=attr2;
		this.attr3=attr3;
	}

	// Property accessors

	public Long getSwrxid() {
		return this.swrxid;
	}

	public void setSwrxid(Long swrxid) {
		this.swrxid = swrxid;
	}

	public String getSwrxno() {
		return this.swrxno;
	}

	public void setSwrxno(String swrxno) {
		this.swrxno = swrxno;
	}

	public String getAcceptedunits() {
		return this.acceptedunits;
	}

	public void setAcceptedunits(String acceptedunits) {
		this.acceptedunits = acceptedunits;
	}

	public Long getTracknum() {
		return this.tracknum;
	}

	public void setTracknum(Long tracknum) {
		this.tracknum = tracknum;
	}

	public Long getReturnvisitnum() {
		return this.returnvisitnum;
	}

	public void setReturnvisitnum(Long returnvisitnum) {
		this.returnvisitnum = returnvisitnum;
	}

	public String getStatementsmark() {
		return this.statementsmark;
	}

	public void setStatementsmark(String statementsmark) {
		this.statementsmark = statementsmark;
	}

	public String getTrackingtags() {
		return this.trackingtags;
	}

	public void setTrackingtags(String trackingtags) {
		this.trackingtags = trackingtags;
	}

	public String getCqcfbx() {
		return this.cqcfbx;
	}

	public void setCqcfbx(String cqcfbx) {
		this.cqcfbx = cqcfbx;
	}

	public Date getInformationreliability() {
		return this.informationreliability;
	}

	public void setInformationreliability(Date informationreliability) {
		this.informationreliability = informationreliability;
	}

	public Date getAutoprinttime() {
		return this.autoprinttime;
	}

	public void setAutoprinttime(Date autoprinttime) {
		this.autoprinttime = autoprinttime;
	}

	public Date getFirstautoprinttime() {
		return this.firstautoprinttime;
	}

	public void setFirstautoprinttime(Date firstautoprinttime) {
		this.firstautoprinttime = firstautoprinttime;
	}

	public String getStationtomark() {
		return this.stationtomark;
	}

	public void setStationtomark(String stationtomark) {
		this.stationtomark = stationtomark;
	}

	public Date getUnderordertime() {
		return this.underordertime;
	}

	public void setUnderordertime(Date underordertime) {
		this.underordertime = underordertime;
	}

	public Date getRecevicereporttime() {
		return this.recevicereporttime;
	}

	public void setRecevicereporttime(Date recevicereporttime) {
		this.recevicereporttime = recevicereporttime;
	}

	public String getLogonstation() {
		return this.logonstation;
	}

	public void setLogonstation(String logonstation) {
		this.logonstation = logonstation;
	}

	public String getReflectpeople() {
		return this.reflectpeople;
	}

	public void setReflectpeople(String reflectpeople) {
		this.reflectpeople = reflectpeople;
	}

	public String getCustomerno() {
		return this.customerno;
	}

	public void setCustomerno(String customerno) {
		this.customerno = customerno;
	}

	public String getReflectunit() {
		return this.reflectunit;
	}

	public void setReflectunit(String reflectunit) {
		this.reflectunit = reflectunit;
	}

	public String getReflectphone() {
		return this.reflectphone;
	}

	public void setReflectphone(String reflectphone) {
		this.reflectphone = reflectphone;
	}

	public String getReflectdistrict() {
		return this.reflectdistrict;
	}

	public void setReflectdistrict(String reflectdistrict) {
		this.reflectdistrict = reflectdistrict;
	}

	public String getAddresshappen() {
		return this.addresshappen;
	}

	public void setAddresshappen(String addresshappen) {
		this.addresshappen = addresshappen;
	}

	public Date getDatehappen() {
		return this.datehappen;
	}

	public void setDatehappen(Date datehappen) {
		this.datehappen = datehappen;
	}

	public String getReflecttype() {
		return this.reflecttype;
	}

	public void setReflecttype(String reflecttype) {
		this.reflecttype = reflecttype;
	}

	public String getReflectcontent() {
		return this.reflectcontent;
	}

	public void setReflectcontent(String reflectcontent) {
		this.reflectcontent = reflectcontent;
	}

	public String getCljb() {
		return this.cljb;
	}

	public void setCljb(String cljb) {
		this.cljb = cljb;
	}

	public String getReflectforms() {
		return this.reflectforms;
	}

	public void setReflectforms(String reflectforms) {
		this.reflectforms = reflectforms;
	}

	public String getReflectsour() {
		return this.reflectsour;
	}

	public void setReflectsour(String reflectsour) {
		this.reflectsour = reflectsour;
	}

	public String getAcceptedremarks() {
		return this.acceptedremarks;
	}

	public void setAcceptedremarks(String acceptedremarks) {
		this.acceptedremarks = acceptedremarks;
	}

	public String getRemarklogonuser() {
		return this.remarklogonuser;
	}

	public void setRemarklogonuser(String remarklogonuser) {
		this.remarklogonuser = remarklogonuser;
	}

	public Date getCompletiontime() {
		return this.completiontime;
	}

	public void setCompletiontime(Date completiontime) {
		this.completiontime = completiontime;
	}

	public String getDealpople() {
		return this.dealpople;
	}

	public void setDealpople(String dealpople) {
		this.dealpople = dealpople;
	}

	public String getDealtype() {
		return this.dealtype;
	}

	public void setDealtype(String dealtype) {
		this.dealtype = dealtype;
	}

	public String getDealcontent() {
		return this.dealcontent;
	}

	public void setDealcontent(String dealcontent) {
		this.dealcontent = dealcontent;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getSolutions() {
		return this.solutions;
	}

	public void setSolutions(String solutions) {
		this.solutions = solutions;
	}

	public String getDealresult() {
		return this.dealresult;
	}

	public void setDealresult(String dealresult) {
		this.dealresult = dealresult;
	}

	public String getDealistimely() {
		return this.dealistimely;
	}

	public void setDealistimely(String dealistimely) {
		this.dealistimely = dealistimely;
	}

	public String getDealremarks() {
		return this.dealremarks;
	}

	public void setDealremarks(String dealremarks) {
		this.dealremarks = dealremarks;
	}

	public String getRepeatsigns() {
		return this.repeatsigns;
	}

	public void setRepeatsigns(String repeatsigns) {
		this.repeatsigns = repeatsigns;
	}

	public String getRepeatrecords() {
		return this.repeatrecords;
	}

	public void setRepeatrecords(String repeatrecords) {
		this.repeatrecords = repeatrecords;
	}

	public String getDeallogonuser() {
		return this.deallogonuser;
	}

	public void setDeallogonuser(String deallogonuser) {
		this.deallogonuser = deallogonuser;
	}

	public String getTrackingprogram() {
		return this.trackingprogram;
	}

	public void setTrackingprogram(String trackingprogram) {
		this.trackingprogram = trackingprogram;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getReflectindustry() {
		return this.reflectindustry;
	}

	public void setReflectindustry(String reflectindustry) {
		this.reflectindustry = reflectindustry;
	}

	public Date getAppointmenttime() {
		return this.appointmenttime;
	}

	public void setAppointmenttime(Date appointmenttime) {
		this.appointmenttime = appointmenttime;
	}

	public Date getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(Date inputdate) {
		this.inputdate = inputdate;
	}

	public String getSellitemsistimely() {
		return this.sellitemsistimely;
	}

	public void setSellitemsistimely(String sellitemsistimely) {
		this.sellitemsistimely = sellitemsistimely;
	}

	public Date getVerifytime() {
		return this.verifytime;
	}

	public void setVerifytime(Date verifytime) {
		this.verifytime = verifytime;
	}

	public String getTaskno() {
		return this.taskno;
	}

	public void setTaskno(String taskno) {
		this.taskno = taskno;
	}

	public String getReplyornot() {
		return this.replyornot;
	}

	public void setReplyornot(String replyornot) {
		this.replyornot = replyornot;
	}

	public String getVerifylogonuser() {
		return this.verifylogonuser;
	}

	public void setVerifylogonuser(String verifylogonuser) {
		this.verifylogonuser = verifylogonuser;
	}

	public String getVerifypeople() {
		return this.verifypeople;
	}

	public void setVerifypeople(String verifypeople) {
		this.verifypeople = verifypeople;
	}

	public String getVerifyremarks() {
		return this.verifyremarks;
	}

	public void setVerifyremarks(String verifyremarks) {
		this.verifyremarks = verifyremarks;
	}

	public String getVerifytimelyrate() {
		return this.verifytimelyrate;
	}

	public void setVerifytimelyrate(String verifytimelyrate) {
		this.verifytimelyrate = verifytimelyrate;
	}

	public String getIsreview() {
		return this.isreview;
	}

	public void setIsreview(String isreview) {
		this.isreview = isreview;
	}

	public String getAcceptedstatus() {
		return this.acceptedstatus;
	}

	public void setAcceptedstatus(String acceptedstatus) {
		this.acceptedstatus = acceptedstatus;
	}

	public Date getAcceptedtime() {
		return this.acceptedtime;
	}

	public void setAcceptedtime(Date acceptedtime) {
		this.acceptedtime = acceptedtime;
	}

	public String getReplylogonuser() {
		return this.replylogonuser;
	}

	public void setReplylogonuser(String replylogonuser) {
		this.replylogonuser = replylogonuser;
	}

	public Date getReplytime() {
		return this.replytime;
	}

	public void setReplytime(Date replytime) {
		this.replytime = replytime;
	}

	public String getReplyforms() {
		return this.replyforms;
	}

	public void setReplyforms(String replyforms) {
		this.replyforms = replyforms;
	}

	public String getReplyremarks() {
		return this.replyremarks;
	}

	public void setReplyremarks(String replyremarks) {
		this.replyremarks = replyremarks;
	}

	public String getVerifyresult() {
		return this.verifyresult;
	}

	public void setVerifyresult(String verifyresult) {
		this.verifyresult = verifyresult;
	}

	public String getNo12319() {
		return this.no12319;
	}

	public void setNo12319(String no12319) {
		this.no12319 = no12319;
	}

	public String getOldsystemno() {
		return this.oldsystemno;
	}

	public void setOldsystemno(String oldsystemno) {
		this.oldsystemno = oldsystemno;
	}

	public String getStatus12319() {
		return this.status12319;
	}

	public void setStatus12319(String status12319) {
		this.status12319 = status12319;
	}

	public String getAttr1() {
		return attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

	public String getAttr2() {
		return attr2;
	}

	public void setAttr2(String attr2) {
		this.attr2 = attr2;
	}

	public String getAttr3() {
		return attr3;
	}

	public void setAttr3(String attr3) {
		this.attr3 = attr3;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	
}