package com.baosight.mode;

/**
 * TbUploadFile generated by MyEclipse Persistence Tools
 */

public class TbUploadFile implements java.io.Serializable {

	// Fields

	private String id;

	private TbArchives tbArchives;

	private String originallyName;

	private String serverName;

	// Constructors

	/** default constructor */
	public TbUploadFile() {
	}

	/** full constructor */
	public TbUploadFile(TbArchives tbArchives, String originallyName,
			String serverName) {
		this.tbArchives = tbArchives;
		this.originallyName = originallyName;
		this.serverName = serverName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbArchives getTbArchives() {
		return this.tbArchives;
	}

	public void setTbArchives(TbArchives tbArchives) {
		this.tbArchives = tbArchives;
	}

	public String getOriginallyName() {
		return this.originallyName;
	}

	public void setOriginallyName(String originallyName) {
		this.originallyName = originallyName;
	}

	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

}