package com.baosight.mode;

/**
 * TbUser generated by MyEclipse Persistence Tools
 */

public class TbUser implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String sex;

	private String userAcc;

	private String pwd;

	private String deptCode;

	private String lvl;

	private String tel;

	private String pst;

	private Long defOrder;

	private Long insure;

	private String ca;

	private String capass;

	private String userdept;

	// Constructors

	/** default constructor */
	public TbUser() {
	}

	/** minimal constructor */
	public TbUser(String userAcc) {
		this.userAcc = userAcc;
	}

	/** full constructor */
	public TbUser(String name, String sex, String userAcc, String pwd,
			String deptCode, String lvl, String tel, String pst, Long defOrder,
			Long insure, String ca, String capass, String userdept) {
		this.name = name;
		this.sex = sex;
		this.userAcc = userAcc;
		this.pwd = pwd;
		this.deptCode = deptCode;
		this.lvl = lvl;
		this.tel = tel;
		this.pst = pst;
		this.defOrder = defOrder;
		this.insure = insure;
		this.ca = ca;
		this.capass = capass;
		this.userdept = userdept;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getUserAcc() {
		return this.userAcc;
	}

	public void setUserAcc(String userAcc) {
		this.userAcc = userAcc;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getLvl() {
		return this.lvl;
	}

	public void setLvl(String lvl) {
		this.lvl = lvl;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPst() {
		return this.pst;
	}

	public void setPst(String pst) {
		this.pst = pst;
	}

	public Long getDefOrder() {
		return this.defOrder;
	}

	public void setDefOrder(Long defOrder) {
		this.defOrder = defOrder;
	}

	public Long getInsure() {
		return this.insure;
	}

	public void setInsure(Long insure) {
		this.insure = insure;
	}

	public String getCa() {
		return this.ca;
	}

	public void setCa(String ca) {
		this.ca = ca;
	}

	public String getCapass() {
		return this.capass;
	}

	public void setCapass(String capass) {
		this.capass = capass;
	}

	public String getUserdept() {
		return this.userdept;
	}

	public void setUserdept(String userdept) {
		this.userdept = userdept;
	}

}