package com.baosight.mode;

import java.util.Date;

/**
 * TbWrit2 generated by MyEclipse Persistence Tools
 */

public class TbWrit2 implements java.io.Serializable {

	// Fields

	private String id;

	private String busId;

	private String wsh;

	private Date applydate;

	private String tjxs;

	private String qtxs;

	private String sjzm;

	private Date createdate;

	// Constructors

	/** default constructor */
	public TbWrit2() {
	}

	/** full constructor */
	public TbWrit2(String busId, String wsh, Date applydate, String tjxs,
			String qtxs, String sjzm, Date createdate) {
		this.busId = busId;
		this.wsh = wsh;
		this.applydate = applydate;
		this.tjxs = tjxs;
		this.qtxs = qtxs;
		this.sjzm = sjzm;
		this.createdate = createdate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	public String getWsh() {
		return this.wsh;
	}

	public void setWsh(String wsh) {
		this.wsh = wsh;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getTjxs() {
		return this.tjxs;
	}

	public void setTjxs(String tjxs) {
		this.tjxs = tjxs;
	}

	public String getQtxs() {
		return this.qtxs;
	}

	public void setQtxs(String qtxs) {
		this.qtxs = qtxs;
	}

	public String getSjzm() {
		return this.sjzm;
	}

	public void setSjzm(String sjzm) {
		this.sjzm = sjzm;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}