package com.baosight.mode;

import java.util.Date;

/**
 * TbWrit4 generated by MyEclipse Persistence Tools
 */

public class TbWrit4 implements java.io.Serializable {

	// Fields

	private String id;

	private String busId;

	private Date applydate;

	private String sqnc;

	private String wsh;

	private String sjzm;

	private Date createdate;

	// Constructors

	/** default constructor */
	public TbWrit4() {
	}

	/** full constructor */
	public TbWrit4(String busId, Date applydate, String sqnc, String wsh,
			String sjzm, Date createdate) {
		this.busId = busId;
		this.applydate = applydate;
		this.sqnc = sqnc;
		this.wsh = wsh;
		this.sjzm = sjzm;
		this.createdate = createdate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getSqnc() {
		return this.sqnc;
	}

	public void setSqnc(String sqnc) {
		this.sqnc = sqnc;
	}

	public String getWsh() {
		return this.wsh;
	}

	public void setWsh(String wsh) {
		this.wsh = wsh;
	}

	public String getSjzm() {
		return this.sjzm;
	}

	public void setSjzm(String sjzm) {
		this.sjzm = sjzm;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}