package com.baosight.mode;

import java.util.Date;

/**
 * TbZfxxgkdfOne generated by MyEclipse Persistence Tools
 */

public class TbZfxxgkdfOne implements java.io.Serializable {

	// Fields

	private String id;

	private String appliName;

	private Date receiveDate;

	private String ifnoName;

	private String offerWay1;

	private String offerWay2;

	private Date sendDate;

	private String lsNo;

	private String attr1;

	// Constructors

	/** default constructor */
	public TbZfxxgkdfOne() {
	}

	/** full constructor */
	public TbZfxxgkdfOne(String appliName, Date receiveDate, String ifnoName,
			String offerWay1, String offerWay2, Date sendDate, String lsNo,
			String attr1) {
		this.appliName = appliName;
		this.receiveDate = receiveDate;
		this.ifnoName = ifnoName;
		this.offerWay1 = offerWay1;
		this.offerWay2 = offerWay2;
		this.sendDate = sendDate;
		this.lsNo = lsNo;
		this.attr1 = attr1;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAppliName() {
		return this.appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getIfnoName() {
		return this.ifnoName;
	}

	public void setIfnoName(String ifnoName) {
		this.ifnoName = ifnoName;
	}

	public String getOfferWay1() {
		return this.offerWay1;
	}

	public void setOfferWay1(String offerWay1) {
		this.offerWay1 = offerWay1;
	}

	public String getOfferWay2() {
		return this.offerWay2;
	}

	public void setOfferWay2(String offerWay2) {
		this.offerWay2 = offerWay2;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getLsNo() {
		return this.lsNo;
	}

	public void setLsNo(String lsNo) {
		this.lsNo = lsNo;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

}