package com.baosight.mode;

import java.util.Date;

/**
 * TbZfxxgksqSjhc generated by MyEclipse Persistence Tools
 */

public class TbZfxxgksqSjhc implements java.io.Serializable {

	// Fields

	private String id;

	private String lsNo;

	private String appliName;

	private Date receiveDate;

	private String infoName;

	private Date restoreDate;

	private String attr1;

	// Constructors

	/** default constructor */
	public TbZfxxgksqSjhc() {
	}

	/** full constructor */
	public TbZfxxgksqSjhc(String lsNo, String appliName, Date receiveDate,
			String infoName, Date restoreDate, String attr1) {
		this.lsNo = lsNo;
		this.appliName = appliName;
		this.receiveDate = receiveDate;
		this.infoName = infoName;
		this.restoreDate = restoreDate;
		this.attr1 = attr1;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLsNo() {
		return this.lsNo;
	}

	public void setLsNo(String lsNo) {
		this.lsNo = lsNo;
	}

	public String getAppliName() {
		return this.appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getInfoName() {
		return this.infoName;
	}

	public void setInfoName(String infoName) {
		this.infoName = infoName;
	}

	public Date getRestoreDate() {
		return this.restoreDate;
	}

	public void setRestoreDate(Date restoreDate) {
		this.restoreDate = restoreDate;
	}

	public String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(String attr1) {
		this.attr1 = attr1;
	}

}