package com.baosight.mode;

// Generated by MyEclipse Persistence Tools

/**
 * VwXzxkId generated by MyEclipse Persistence Tools
 */
public class VwXzxkId extends AbstractVwXzxkId implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public VwXzxkId() {
	}

	/** full constructor */
	public VwXzxkId(String activtiyid, String actstate, String processname,
			String porcessstate, String processid, String partname,
			String username, String starttime, String endtime, String slh,
			String projectname, String projectaddress, String applier,
			String wwgsstatus, String sjtime, String bltime, String jdtime,
			String tztime) {
		super(activtiyid, actstate, processname, porcessstate, processid,
				partname, username, starttime, endtime, slh, projectname,
				projectaddress, applier, wwgsstatus, sjtime, bltime, jdtime,
				tztime);
	}

}
