package com.baosight.sms.mode;

import java.util.HashSet;
import java.util.Set;

/**
 * SmsTransferInfo generated by MyEclipse Persistence Tools
 */

public class SmsTransferInfo implements java.io.Serializable {

	// Fields

	private String id;

	private String receiveMobile;

	private String receiveName;

	private String receiveDept;

	private String senderMobile;

	private String bz;

	private String receiveType;

	private Set smsTransferLists = new HashSet(0);

	// Constructors

	/** default constructor */
	public SmsTransferInfo() {
	}

	/** full constructor */
	public SmsTransferInfo(String receiveMobile, String receiveName,
			String receiveDept, String senderMobile, String bz,
			String receiveType, Set smsTransferLists) {
		this.receiveMobile = receiveMobile;
		this.receiveName = receiveName;
		this.receiveDept = receiveDept;
		this.senderMobile = senderMobile;
		this.bz = bz;
		this.receiveType = receiveType;
		this.smsTransferLists = smsTransferLists;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getReceiveMobile() {
		return this.receiveMobile;
	}

	public void setReceiveMobile(String receiveMobile) {
		this.receiveMobile = receiveMobile;
	}

	public String getReceiveName() {
		return this.receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	public String getReceiveDept() {
		return this.receiveDept;
	}

	public void setReceiveDept(String receiveDept) {
		this.receiveDept = receiveDept;
	}

	public String getSenderMobile() {
		return this.senderMobile;
	}

	public void setSenderMobile(String senderMobile) {
		this.senderMobile = senderMobile;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getReceiveType() {
		return this.receiveType;
	}

	public void setReceiveType(String receiveType) {
		this.receiveType = receiveType;
	}

	public Set getSmsTransferLists() {
		return this.smsTransferLists;
	}

	public void setSmsTransferLists(Set smsTransferLists) {
		this.smsTransferLists = smsTransferLists;
	}

}