package com.baosight.sms.mode;

/**
 * SmsTransferList generated by MyEclipse Persistence Tools
 */

public class SmsTransferList implements java.io.Serializable {

	// Fields

	private String id;

	private SmsTransferInfo smsTransferInfo;

	private String senderMobile;

	private String senderName;

	private String senderDept;

	private String senderType;

	private String bz1;

	private String bz2;

	// Constructors

	/** default constructor */
	public SmsTransferList() {
	}

	/** full constructor */
	public SmsTransferList(SmsTransferInfo smsTransferInfo,
			String senderMobile, String senderName, String senderDept,
			String senderType, String bz1, String bz2) {
		this.smsTransferInfo = smsTransferInfo;
		this.senderMobile = senderMobile;
		this.senderName = senderName;
		this.senderDept = senderDept;
		this.senderType = senderType;
		this.bz1 = bz1;
		this.bz2 = bz2;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SmsTransferInfo getSmsTransferInfo() {
		return this.smsTransferInfo;
	}

	public void setSmsTransferInfo(SmsTransferInfo smsTransferInfo) {
		this.smsTransferInfo = smsTransferInfo;
	}

	public String getSenderMobile() {
		return this.senderMobile;
	}

	public void setSenderMobile(String senderMobile) {
		this.senderMobile = senderMobile;
	}

	public String getSenderName() {
		return this.senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getSenderDept() {
		return this.senderDept;
	}

	public void setSenderDept(String senderDept) {
		this.senderDept = senderDept;
	}

	public String getSenderType() {
		return this.senderType;
	}

	public void setSenderType(String senderType) {
		this.senderType = senderType;
	}

	public String getBz1() {
		return this.bz1;
	}

	public void setBz1(String bz1) {
		this.bz1 = bz1;
	}

	public String getBz2() {
		return this.bz2;
	}

	public void setBz2(String bz2) {
		this.bz2 = bz2;
	}

}