package com.baosight.tech.mode;

import java.util.Date;

/**
 * TbTechResult generated by MyEclipse Persistence Tools
 */

public class TbTechResult implements java.io.Serializable {

	// Fields

	private String id;

	private String itemName;

	private String bearUnit;

	private String itemPrincipal;

	private Date startTime;

	private Date endTime;

	private String needSense;

	private String contentKey;

	private String plan;

	private String expectEffect;

	private String itemFrom;

	private String together;

	private String itemInvest;

	private String itemBudget;

	private String workHeadway;

	private String issuePaper;

	private String issuePaperName;

	private String artFile1;

	private String artFile2;

	private String artFile3;

	private String artFile4;

	private String artFile5;

	private String artFile6;

	private String artFile7;

	private String artFile8;

	private String artFile9;

	private String artFile10;

	private String manageFile1;

	private String manageFile2;

	private String manageFile3;

	private String manageFile4;

	private String manageFile5;

	private String manageFile6;

	private String manageFile7;

	private String manageFile8;

	private String manageFile9;

	private String manageFile10;

	private String temp;

	private String temp1;

	private String temp2;

	private String temp3;

	private String temp4;

	private String temp5;

	private String temp6;

	private String temp7;

	private String temp8;

	private String temp9;

	private String temp10;

	private String temp11;

	private String temp12;

	private String temp13;

	private String temp14;

	private String temp15;

	// Constructors

	/** default constructor */
	public TbTechResult() {
	}

	/** full constructor */
	public TbTechResult(String itemName, String bearUnit, String itemPrincipal,
			Date startTime, Date endTime, String needSense, String contentKey,
			String plan, String expectEffect, String itemFrom, String together,
			String itemInvest, String itemBudget, String workHeadway,
			String issuePaper, String issuePaperName, String artFile1,
			String artFile2, String artFile3, String artFile4, String artFile5,
			String artFile6, String artFile7, String artFile8, String artFile9,
			String artFile10, String manageFile1, String manageFile2,
			String manageFile3, String manageFile4, String manageFile5,
			String manageFile6, String manageFile7, String manageFile8,
			String manageFile9, String manageFile10, String temp, String temp1,
			String temp2, String temp3, String temp4, String temp5,
			String temp6, String temp7, String temp8, String temp9,
			String temp10, String temp11, String temp12, String temp13,
			String temp14, String temp15) {
		this.itemName = itemName;
		this.bearUnit = bearUnit;
		this.itemPrincipal = itemPrincipal;
		this.startTime = startTime;
		this.endTime = endTime;
		this.needSense = needSense;
		this.contentKey = contentKey;
		this.plan = plan;
		this.expectEffect = expectEffect;
		this.itemFrom = itemFrom;
		this.together = together;
		this.itemInvest = itemInvest;
		this.itemBudget = itemBudget;
		this.workHeadway = workHeadway;
		this.issuePaper = issuePaper;
		this.issuePaperName = issuePaperName;
		this.artFile1 = artFile1;
		this.artFile2 = artFile2;
		this.artFile3 = artFile3;
		this.artFile4 = artFile4;
		this.artFile5 = artFile5;
		this.artFile6 = artFile6;
		this.artFile7 = artFile7;
		this.artFile8 = artFile8;
		this.artFile9 = artFile9;
		this.artFile10 = artFile10;
		this.manageFile1 = manageFile1;
		this.manageFile2 = manageFile2;
		this.manageFile3 = manageFile3;
		this.manageFile4 = manageFile4;
		this.manageFile5 = manageFile5;
		this.manageFile6 = manageFile6;
		this.manageFile7 = manageFile7;
		this.manageFile8 = manageFile8;
		this.manageFile9 = manageFile9;
		this.manageFile10 = manageFile10;
		this.temp = temp;
		this.temp1 = temp1;
		this.temp2 = temp2;
		this.temp3 = temp3;
		this.temp4 = temp4;
		this.temp5 = temp5;
		this.temp6 = temp6;
		this.temp7 = temp7;
		this.temp8 = temp8;
		this.temp9 = temp9;
		this.temp10 = temp10;
		this.temp11 = temp11;
		this.temp12 = temp12;
		this.temp13 = temp13;
		this.temp14 = temp14;
		this.temp15 = temp15;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getBearUnit() {
		return this.bearUnit;
	}

	public void setBearUnit(String bearUnit) {
		this.bearUnit = bearUnit;
	}

	public String getItemPrincipal() {
		return this.itemPrincipal;
	}

	public void setItemPrincipal(String itemPrincipal) {
		this.itemPrincipal = itemPrincipal;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getNeedSense() {
		return this.needSense;
	}

	public void setNeedSense(String needSense) {
		this.needSense = needSense;
	}

	public String getContentKey() {
		return this.contentKey;
	}

	public void setContentKey(String contentKey) {
		this.contentKey = contentKey;
	}

	public String getPlan() {
		return this.plan;
	}

	public void setPlan(String plan) {
		this.plan = plan;
	}

	public String getExpectEffect() {
		return this.expectEffect;
	}

	public void setExpectEffect(String expectEffect) {
		this.expectEffect = expectEffect;
	}

	public String getItemFrom() {
		return this.itemFrom;
	}

	public void setItemFrom(String itemFrom) {
		this.itemFrom = itemFrom;
	}

	public String getTogether() {
		return this.together;
	}

	public void setTogether(String together) {
		this.together = together;
	}

	public String getItemInvest() {
		return this.itemInvest;
	}

	public void setItemInvest(String itemInvest) {
		this.itemInvest = itemInvest;
	}

	public String getItemBudget() {
		return this.itemBudget;
	}

	public void setItemBudget(String itemBudget) {
		this.itemBudget = itemBudget;
	}

	public String getWorkHeadway() {
		return this.workHeadway;
	}

	public void setWorkHeadway(String workHeadway) {
		this.workHeadway = workHeadway;
	}

	public String getIssuePaper() {
		return this.issuePaper;
	}

	public void setIssuePaper(String issuePaper) {
		this.issuePaper = issuePaper;
	}

	public String getIssuePaperName() {
		return this.issuePaperName;
	}

	public void setIssuePaperName(String issuePaperName) {
		this.issuePaperName = issuePaperName;
	}

	public String getArtFile1() {
		return this.artFile1;
	}

	public void setArtFile1(String artFile1) {
		this.artFile1 = artFile1;
	}

	public String getArtFile2() {
		return this.artFile2;
	}

	public void setArtFile2(String artFile2) {
		this.artFile2 = artFile2;
	}

	public String getArtFile3() {
		return this.artFile3;
	}

	public void setArtFile3(String artFile3) {
		this.artFile3 = artFile3;
	}

	public String getArtFile4() {
		return this.artFile4;
	}

	public void setArtFile4(String artFile4) {
		this.artFile4 = artFile4;
	}

	public String getArtFile5() {
		return this.artFile5;
	}

	public void setArtFile5(String artFile5) {
		this.artFile5 = artFile5;
	}

	public String getArtFile6() {
		return this.artFile6;
	}

	public void setArtFile6(String artFile6) {
		this.artFile6 = artFile6;
	}

	public String getArtFile7() {
		return this.artFile7;
	}

	public void setArtFile7(String artFile7) {
		this.artFile7 = artFile7;
	}

	public String getArtFile8() {
		return this.artFile8;
	}

	public void setArtFile8(String artFile8) {
		this.artFile8 = artFile8;
	}

	public String getArtFile9() {
		return this.artFile9;
	}

	public void setArtFile9(String artFile9) {
		this.artFile9 = artFile9;
	}

	public String getArtFile10() {
		return this.artFile10;
	}

	public void setArtFile10(String artFile10) {
		this.artFile10 = artFile10;
	}

	public String getManageFile1() {
		return this.manageFile1;
	}

	public void setManageFile1(String manageFile1) {
		this.manageFile1 = manageFile1;
	}

	public String getManageFile2() {
		return this.manageFile2;
	}

	public void setManageFile2(String manageFile2) {
		this.manageFile2 = manageFile2;
	}

	public String getManageFile3() {
		return this.manageFile3;
	}

	public void setManageFile3(String manageFile3) {
		this.manageFile3 = manageFile3;
	}

	public String getManageFile4() {
		return this.manageFile4;
	}

	public void setManageFile4(String manageFile4) {
		this.manageFile4 = manageFile4;
	}

	public String getManageFile5() {
		return this.manageFile5;
	}

	public void setManageFile5(String manageFile5) {
		this.manageFile5 = manageFile5;
	}

	public String getManageFile6() {
		return this.manageFile6;
	}

	public void setManageFile6(String manageFile6) {
		this.manageFile6 = manageFile6;
	}

	public String getManageFile7() {
		return this.manageFile7;
	}

	public void setManageFile7(String manageFile7) {
		this.manageFile7 = manageFile7;
	}

	public String getManageFile8() {
		return this.manageFile8;
	}

	public void setManageFile8(String manageFile8) {
		this.manageFile8 = manageFile8;
	}

	public String getManageFile9() {
		return this.manageFile9;
	}

	public void setManageFile9(String manageFile9) {
		this.manageFile9 = manageFile9;
	}

	public String getManageFile10() {
		return this.manageFile10;
	}

	public void setManageFile10(String manageFile10) {
		this.manageFile10 = manageFile10;
	}

	public String getTemp() {
		return this.temp;
	}

	public void setTemp(String temp) {
		this.temp = temp;
	}

	public String getTemp1() {
		return this.temp1;
	}

	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}

	public String getTemp2() {
		return this.temp2;
	}

	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}

	public String getTemp3() {
		return this.temp3;
	}

	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}

	public String getTemp4() {
		return this.temp4;
	}

	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}

	public String getTemp5() {
		return this.temp5;
	}

	public void setTemp5(String temp5) {
		this.temp5 = temp5;
	}

	public String getTemp6() {
		return this.temp6;
	}

	public void setTemp6(String temp6) {
		this.temp6 = temp6;
	}

	public String getTemp7() {
		return this.temp7;
	}

	public void setTemp7(String temp7) {
		this.temp7 = temp7;
	}

	public String getTemp8() {
		return this.temp8;
	}

	public void setTemp8(String temp8) {
		this.temp8 = temp8;
	}

	public String getTemp9() {
		return this.temp9;
	}

	public void setTemp9(String temp9) {
		this.temp9 = temp9;
	}

	public String getTemp10() {
		return this.temp10;
	}

	public void setTemp10(String temp10) {
		this.temp10 = temp10;
	}

	public String getTemp11() {
		return this.temp11;
	}

	public void setTemp11(String temp11) {
		this.temp11 = temp11;
	}

	public String getTemp12() {
		return this.temp12;
	}

	public void setTemp12(String temp12) {
		this.temp12 = temp12;
	}

	public String getTemp13() {
		return this.temp13;
	}

	public void setTemp13(String temp13) {
		this.temp13 = temp13;
	}

	public String getTemp14() {
		return this.temp14;
	}

	public void setTemp14(String temp14) {
		this.temp14 = temp14;
	}

	public String getTemp15() {
		return this.temp15;
	}

	public void setTemp15(String temp15) {
		this.temp15 = temp15;
	}

}