package com.baosight.tech.mode;

/**
 * TbTechMapShare generated by MyEclipse Persistence Tools
 */

public class TbTechMapShare implements java.io.Serializable {

	// Fields

	private String id;

	private String unitName;

	private String getTime;

	private String applyReason;

	private String mapScope;

	private String mapContent;

	private String attachment1;

	private String attachment2;

	private String a1;

	private String a2;

	// Constructors

	/** default constructor */
	public TbTechMapShare() {
	}

	/** minimal constructor */
	public TbTechMapShare(String unitName, String getTime) {
		this.unitName = unitName;
		this.getTime = getTime;
	}

	/** full constructor */
	public TbTechMapShare(String unitName, String getTime, String applyReason,
			String mapScope, String mapContent, String attachment1,
			String attachment2, String a1, String a2) {
		this.unitName = unitName;
		this.getTime = getTime;
		this.applyReason = applyReason;
		this.mapScope = mapScope;
		this.mapContent = mapContent;
		this.attachment1 = attachment1;
		this.attachment2 = attachment2;
		this.a1 = a1;
		this.a2 = a2;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getGetTime() {
		return this.getTime;
	}

	public void setGetTime(String getTime) {
		this.getTime = getTime;
	}

	public String getApplyReason() {
		return this.applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	public String getMapScope() {
		return this.mapScope;
	}

	public void setMapScope(String mapScope) {
		this.mapScope = mapScope;
	}

	public String getMapContent() {
		return this.mapContent;
	}

	public void setMapContent(String mapContent) {
		this.mapContent = mapContent;
	}

	public String getAttachment1() {
		return this.attachment1;
	}

	public void setAttachment1(String attachment1) {
		this.attachment1 = attachment1;
	}

	public String getAttachment2() {
		return this.attachment2;
	}

	public void setAttachment2(String attachment2) {
		this.attachment2 = attachment2;
	}

	public String getA1() {
		return this.a1;
	}

	public void setA1(String a1) {
		this.a1 = a1;
	}

	public String getA2() {
		return this.a2;
	}

	public void setA2(String a2) {
		this.a2 = a2;
	}

}