package com.baosight.tech.mode;

import java.util.Date;

/**
 * TbTechStandard generated by MyEclipse Persistence Tools
 */

public class TbTechStandard implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String levels;

	private String pubDepartment;

	private Date pubTime;

	private String content;

	private String fileAttach;

	private String a1;

	private String a2;

	private String a3;

	private String a4;

	private String a5;

	// Constructors

	/** default constructor */
	public TbTechStandard() {
	}

	/** full constructor */
	public TbTechStandard(String name, String levels, String pubDepartment,
			Date pubTime, String content, String fileAttach, String a1,
			String a2, String a3, String a4, String a5) {
		this.name = name;
		this.levels = levels;
		this.pubDepartment = pubDepartment;
		this.pubTime = pubTime;
		this.content = content;
		this.fileAttach = fileAttach;
		this.a1 = a1;
		this.a2 = a2;
		this.a3 = a3;
		this.a4 = a4;
		this.a5 = a5;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevels() {
		return this.levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	public String getPubDepartment() {
		return this.pubDepartment;
	}

	public void setPubDepartment(String pubDepartment) {
		this.pubDepartment = pubDepartment;
	}

	public Date getPubTime() {
		return this.pubTime;
	}

	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getFileAttach() {
		return this.fileAttach;
	}

	public void setFileAttach(String fileAttach) {
		this.fileAttach = fileAttach;
	}

	public String getA1() {
		return this.a1;
	}

	public void setA1(String a1) {
		this.a1 = a1;
	}

	public String getA2() {
		return this.a2;
	}

	public void setA2(String a2) {
		this.a2 = a2;
	}

	public String getA3() {
		return this.a3;
	}

	public void setA3(String a3) {
		this.a3 = a3;
	}

	public String getA4() {
		return this.a4;
	}

	public void setA4(String a4) {
		this.a4 = a4;
	}

	public String getA5() {
		return this.a5;
	}

	public void setA5(String a5) {
		this.a5 = a5;
	}

}