package com.baosight.infocenter.docsend.mode;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbDocSendXxzx generated by MyEclipse Persistence Tools
 */

public class TbDocSendXxzx implements java.io.Serializable {

	// Fields

	private String id;

	private String fileSecret;

	private String sign;

	private String fileTitle;

	private String fileDept;

	private String sendMain;

	private String sendSecond;

	private String topicWord;

	private String draftUser;

	private String chargeUser;

	private String fileNo;

	private Long fileNum;

	private String printUser;

	private String collateUser;

	private Date fileDate;

	private String secret1;

	private String secret2;

	private Long filePages;

	private String sendFileType;

	private String docState;

	private String fileCategory;

	private String fileType;

	private String sendFileTypeX;

	private Set tbDocsendControlXxzxes = new HashSet(0);

	// Constructors

	/** default constructor */
	public TbDocSendXxzx() {
	}

	/** full constructor */
	public TbDocSendXxzx(String fileSecret, String sign, String fileTitle,
			String fileDept, String sendMain, String sendSecond,
			String topicWord, String draftUser, String chargeUser,
			String fileNo, Long fileNum, String printUser, String collateUser,
			Date fileDate, String secret1, String secret2, Long filePages,
			String sendFileType, String docState, String fileCategory,
			String fileType, String sendFileTypeX, Set tbDocsendControlXxzxes) {
		this.fileSecret = fileSecret;
		this.sign = sign;
		this.fileTitle = fileTitle;
		this.fileDept = fileDept;
		this.sendMain = sendMain;
		this.sendSecond = sendSecond;
		this.topicWord = topicWord;
		this.draftUser = draftUser;
		this.chargeUser = chargeUser;
		this.fileNo = fileNo;
		this.fileNum = fileNum;
		this.printUser = printUser;
		this.collateUser = collateUser;
		this.fileDate = fileDate;
		this.secret1 = secret1;
		this.secret2 = secret2;
		this.filePages = filePages;
		this.sendFileType = sendFileType;
		this.docState = docState;
		this.fileCategory = fileCategory;
		this.fileType = fileType;
		this.sendFileTypeX = sendFileTypeX;
		this.tbDocsendControlXxzxes = tbDocsendControlXxzxes;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileSecret() {
		return this.fileSecret;
	}

	public void setFileSecret(String fileSecret) {
		this.fileSecret = fileSecret;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getFileTitle() {
		return this.fileTitle;
	}

	public void setFileTitle(String fileTitle) {
		this.fileTitle = fileTitle;
	}

	public String getFileDept() {
		return this.fileDept;
	}

	public void setFileDept(String fileDept) {
		this.fileDept = fileDept;
	}

	public String getSendMain() {
		return this.sendMain;
	}

	public void setSendMain(String sendMain) {
		this.sendMain = sendMain;
	}

	public String getSendSecond() {
		return this.sendSecond;
	}

	public void setSendSecond(String sendSecond) {
		this.sendSecond = sendSecond;
	}

	public String getTopicWord() {
		return this.topicWord;
	}

	public void setTopicWord(String topicWord) {
		this.topicWord = topicWord;
	}

	public String getDraftUser() {
		return this.draftUser;
	}

	public void setDraftUser(String draftUser) {
		this.draftUser = draftUser;
	}

	public String getChargeUser() {
		return this.chargeUser;
	}

	public void setChargeUser(String chargeUser) {
		this.chargeUser = chargeUser;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public Long getFileNum() {
		return this.fileNum;
	}

	public void setFileNum(Long fileNum) {
		this.fileNum = fileNum;
	}

	public String getPrintUser() {
		return this.printUser;
	}

	public void setPrintUser(String printUser) {
		this.printUser = printUser;
	}

	public String getCollateUser() {
		return this.collateUser;
	}

	public void setCollateUser(String collateUser) {
		this.collateUser = collateUser;
	}

	public Date getFileDate() {
		return this.fileDate;
	}

	public void setFileDate(Date fileDate) {
		this.fileDate = fileDate;
	}

	public String getSecret1() {
		return this.secret1;
	}

	public void setSecret1(String secret1) {
		this.secret1 = secret1;
	}

	public String getSecret2() {
		return this.secret2;
	}

	public void setSecret2(String secret2) {
		this.secret2 = secret2;
	}

	public Long getFilePages() {
		return this.filePages;
	}

	public void setFilePages(Long filePages) {
		this.filePages = filePages;
	}

	public String getSendFileType() {
		return this.sendFileType;
	}

	public void setSendFileType(String sendFileType) {
		this.sendFileType = sendFileType;
	}

	public String getDocState() {
		return this.docState;
	}

	public void setDocState(String docState) {
		this.docState = docState;
	}

	public String getFileCategory() {
		return this.fileCategory;
	}

	public void setFileCategory(String fileCategory) {
		this.fileCategory = fileCategory;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getSendFileTypeX() {
		return this.sendFileTypeX;
	}

	public void setSendFileTypeX(String sendFileTypeX) {
		this.sendFileTypeX = sendFileTypeX;
	}

	public Set getTbDocsendControlXxzxes() {
		return this.tbDocsendControlXxzxes;
	}

	public void setTbDocsendControlXxzxes(Set tbDocsendControlXxzxes) {
		this.tbDocsendControlXxzxes = tbDocsendControlXxzxes;
	}

}