package com.baosight.fax.mode;

import java.util.Date;

/**
 * TbFaxSchedule generated by MyEclipse Persistence Tools
 */

public class TbFaxSchedule implements java.io.Serializable {

	// Fields

	private String id;

	private String content;

	private Date senddate;

	private String sender;

	private String senderid;

	private String fax;

	private String sendtype;

	private String state;

	private String recman;

	private String recmanid;

	private String recgroupid;

	private String senddeptid;

	private String faxflag;

	private String fileName;
	
	private String content1;
	
	private String fileid;
	
	private String issms;
	
	private String mphone;

	// Constructors

	/** default constructor */
	public TbFaxSchedule() {
	}

	/** full constructor */
	public TbFaxSchedule(String content, Date senddate, String sender,
			String senderid, String fax, String sendtype, String state,
			String recman, String recmanid, String recgroupid,
			String senddeptid, String faxflag, String fileName) {
		this.content = content;
		this.senddate = senddate;
		this.sender = sender;
		this.senderid = senderid;
		this.fax = fax;
		this.sendtype = sendtype;
		this.state = state;
		this.recman = recman;
		this.recmanid = recmanid;
		this.recgroupid = recgroupid;
		this.senddeptid = senddeptid;
		this.faxflag = faxflag;
		this.fileName = fileName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSenddate() {
		return this.senddate;
	}

	public void setSenddate(Date senddate) {
		this.senddate = senddate;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getSenderid() {
		return this.senderid;
	}

	public void setSenderid(String senderid) {
		this.senderid = senderid;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getSendtype() {
		return this.sendtype;
	}

	public void setSendtype(String sendtype) {
		this.sendtype = sendtype;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRecman() {
		return this.recman;
	}

	public void setRecman(String recman) {
		this.recman = recman;
	}

	public String getRecmanid() {
		return this.recmanid;
	}

	public void setRecmanid(String recmanid) {
		this.recmanid = recmanid;
	}

	public String getRecgroupid() {
		return this.recgroupid;
	}

	public void setRecgroupid(String recgroupid) {
		this.recgroupid = recgroupid;
	}

	public String getSenddeptid() {
		return this.senddeptid;
	}

	public void setSenddeptid(String senddeptid) {
		this.senddeptid = senddeptid;
	}

	public String getFaxflag() {
		return this.faxflag;
	}

	public void setFaxflag(String faxflag) {
		this.faxflag = faxflag;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getContent1() {
		return content1;
	}

	public void setContent1(String content1) {
		this.content1 = content1;
	}

	public String getFileid() {
		return fileid;
	}

	public void setFileid(String fileid) {
		this.fileid = fileid;
	}

	public String getIssms() {
		return issms;
	}

	public void setIssms(String issms) {
		this.issms = issms;
	}

	public String getMphone() {
		return mphone;
	}

	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

}